/-
Copyright (c) 2026 Robert Kirkby. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Robert Kirkby
-/
import AbstractDynamicProgramming.ADP

/-!
# ADPs generated by RDPs, MDPs and Q-factors

Sargent and Stachurski, *Dynamic Programming*, Volume 1, Examples 9.1.1–9.1.4, 9.2.1,
Corollary 9.2.2, Exercise 9.2.2 and Proposition 9.2.3 (pp. 295–299).

* Example 9.1.1: an RDP `R` generates the ADP `A_R = (V, {T_σ})`, with greedy and anti-greedy
  policies giving the greatest and least elements of `{T_σ v}`.
* Corollary 9.2.2: if `R` is globally stable then `A_R` is max-stable (Lemma 9.1.1 and
  Proposition 9.2.1).
* Proposition 9.2.3: if `V` is an order interval, `A_R` is well-posed iff it is order stable
  (by Knaster–Tarski on `[v₁, v]` and `[v, v₂]`).
* Examples 9.1.2 and 9.2.1: the ADP of an MDP, with `v_σ = (I − βP_σ)⁻¹r_σ`.
* Example 9.1.3 and Exercise 9.2.2: the Q-factor ADP on `ℝ^{X × A}` is an ADP and is max-stable.
* Example 9.1.4: the risk-sensitive Q-factor operators form an ADP.
-/

open Finset Matrix Filter Topology Function Set

namespace SargentStachurski.AbstractDynamicProgramming

attribute [local instance] Matrix.linftyOpNormedRing Matrix.linftyOpNormedAlgebra

namespace RDP

variable {X A : Type*} [Fintype X] [Fintype A] (R : RDP X A)

/-- **Example 9.1.1** (p. 295): the ADP `A_R = (V, {T_σ}_{σ ∈ Σ})` generated by an RDP. -/
noncomputable def toADP : ADP R.V R.Policy where
  T σ v := ⟨R.Tσ σ.1 v, R.Tσ_mapsTo σ.2 v.2⟩
  exists_greedy v := ⟨R.greedyPolicy v, fun τ =>
    (R.Tσ_le_T τ.2 v).trans_eq (R.Tσ_eq_T_of_isGreedy (R.isGreedy_greedy v)).symm⟩
  exists_minGreedy v := by
    obtain ⟨⟨σ, hσ⟩, hle⟩ := R.isLeast_Tσ v
    refine ⟨σ, fun τ => ?_⟩
    change R.Tσ σ.1 v ≤ R.Tσ τ.1 v
    have hσ' : R.Tσ σ.1 v = R.Tσ (R.antiGreedy v) v := hσ
    rw [hσ']
    exact hle ⟨τ, rfl⟩

theorem toADP_T (σ : R.Policy) (v : R.V) : (R.toADP.T σ v : X → ℝ) = R.Tσ σ.1 v := rfl

/-- The ADP of a well-posed RDP is well-posed. -/
theorem toADP_wellPosed {R : RDP X A} (hw : R.WellPosed) : R.toADP.WellPosed := fun σ => by
  refine ⟨⟨R.vσ σ.1, vσ_mem hw σ.2⟩, Subtype.ext (isFixedPt_vσ hw σ.2).eq, fun w hw' => ?_⟩
  exact Subtype.ext (eq_vσ_of_isFixedPt hw σ.2 w.2 (congrArg Subtype.val hw'.eq))

/-- The `σ`-value functions of `A_R` are those of `R`. -/
theorem toADP_vσ {R : RDP X A} (hw : R.WellPosed) (hw' : R.toADP.WellPosed) (σ : R.Policy) :
    (R.toADP.vσ hw' σ : X → ℝ) = R.vσ σ.1 :=
  eq_vσ_of_isFixedPt hw σ.2 (R.toADP.vσ hw' σ).2
    (congrArg Subtype.val (ADP.isFixedPt_vσ hw' σ).eq)

/-- The Bellman operator of `A_R` is the Bellman operator of `R` (p. 298). -/
theorem toADP_bellman (v : R.V) : (R.toADP.bellman v : X → ℝ) = R.T v := by
  have h1 := (R.toADP.isGreedy_iff v (R.greedyPolicy v)).1 fun τ =>
    (R.Tσ_le_T τ.2 v).trans_eq (R.Tσ_eq_T_of_isGreedy (R.isGreedy_greedy v)).symm
  rw [← h1]
  exact R.Tσ_eq_T_of_isGreedy (R.isGreedy_greedy v)

/-- Lemma 9.1.1 for RDPs: if `R` is globally stable, `A_R` is order stable. -/
theorem toADP_isOrderStable {R : RDP X A} (hR : R.IsGloballyStable) : R.toADP.IsOrderStable :=
  fun σ => orderStable_restrict (R.Tσ_mapsTo σ.2) (R.Tσ_monotoneOn σ.2) (hR σ.1 σ.2)

/-- **Corollary 9.2.2** (p. 299): if `R` is globally stable, `A_R` is max-stable. -/
theorem toADP_isMaxStable {R : RDP X A} (hR : R.IsGloballyStable) : R.toADP.IsMaxStable :=
  have := R.policy_nonempty
  (toADP_isOrderStable hR).isMaxStable

/-- **Proposition 9.2.3** (p. 299): if `V = [v₁, v₂]` then `A_R` is well-posed iff it is order
stable. -/
theorem toADP_wellPosed_iff {R : RDP X A} {v₁ v₂ : X → ℝ} (h12 : v₁ ≤ v₂)
    (hV : R.V = Icc v₁ v₂) : R.toADP.WellPosed ↔ R.toADP.IsOrderStable := by
  refine ⟨fun hw σ => ?_, fun h => h.wellPosed⟩
  have hu := ADP.isFixedPt_vσ hw σ
  have huniq : ∀ w : R.V, IsFixedPt (R.toADP.T σ) w → w = R.toADP.vσ hw σ := fun w hw' =>
    ADP.eq_vσ_of_isFixedPt hw hw'
  have hmono : MonotoneOn (R.Tσ σ.1) R.V := R.Tσ_monotoneOn σ.2
  have hmaps : MapsTo (R.Tσ σ.1) R.V R.V := R.Tσ_mapsTo σ.2
  have hsub : ∀ {a b : X → ℝ}, v₁ ≤ a → b ≤ v₂ → Icc a b ⊆ R.V := fun ha hb z hz => by
    rw [hV]
    exact ⟨ha.trans hz.1, hz.2.trans hb⟩
  have hv1 : v₁ ∈ R.V := by rw [hV]; exact ⟨le_rfl, h12⟩
  have hv2 : v₂ ∈ R.V := by rw [hV]; exact ⟨h12, le_rfl⟩
  refine orderStable_of_up_down hu (fun v hv => ?_) fun v hv => ?_
  · -- `T_σ` maps `[v, v₂]` into itself
    have hv' : (v : X → ℝ) ≤ R.Tσ σ.1 v := hv
    have hvV : (v : X → ℝ) ∈ Icc v₁ v₂ := hV ▸ v.2
    have hm : MapsTo (R.Tσ σ.1) (Icc (v : X → ℝ) v₂) (Icc (v : X → ℝ) v₂) := fun z hz => by
      have hzV := hsub hvV.1 le_rfl hz
      have h2 : R.Tσ σ.1 z ∈ Icc v₁ v₂ := hV ▸ hmaps hzV
      exact ⟨hv'.trans (hmono v.2 hzV hz.1), h2.2⟩
    obtain ⟨a, ha, -, -, hafix, -⟩ :=
      knaster_tarski hvV.2 hm (hmono.mono (hsub hvV.1 le_rfl))
    have haV : a ∈ R.V := hsub hvV.1 le_rfl ha
    have := huniq ⟨a, haV⟩ (Subtype.ext hafix.eq)
    rw [← this]
    exact ha.1
  · have hv' : R.Tσ σ.1 v ≤ (v : X → ℝ) := hv
    have hvV : (v : X → ℝ) ∈ Icc v₁ v₂ := hV ▸ v.2
    have hm : MapsTo (R.Tσ σ.1) (Icc v₁ (v : X → ℝ)) (Icc v₁ (v : X → ℝ)) := fun z hz => by
      have hzV := hsub le_rfl hvV.2 hz
      have h2 : R.Tσ σ.1 z ∈ Icc v₁ v₂ := hV ▸ hmaps hzV
      exact ⟨h2.1, (hmono hzV v.2 hz.2).trans hv'⟩
    obtain ⟨a, ha, -, -, hafix, -⟩ :=
      knaster_tarski hvV.1 hm (hmono.mono (hsub le_rfl hvV.2))
    have haV : a ∈ R.V := hsub le_rfl hvV.2 ha
    have := huniq ⟨a, haV⟩ (Subtype.ext hafix.eq)
    rw [← this]
    exact ha.2

end RDP

/-! ### MDPs (Examples 9.1.2 and 9.2.1) -/

/-- A Markov decision process `M = (Γ, β, r, P)` (§5.1.1, restated). -/
structure MDP (X A : Type*) [Fintype X] [Fintype A] where
  Γ : X → Finset A
  Γ_nonempty : ∀ x, (Γ x).Nonempty
  β : ℝ
  β_pos : 0 < β
  β_lt_one : β < 1
  r : X → A → ℝ
  P : X → A → X → ℝ
  P_nonneg : ∀ x a x', 0 ≤ P x a x'
  P_rowsum : ∀ x a, ∑ x', P x a x' = 1

namespace MDP

variable {X A : Type*} [Fintype X] [Fintype A] (M : MDP X A)

/-- The closed-loop matrix `P_σ(x, x') = P(x, σ(x), x')`. -/
def Pσ (σ : X → A) : Matrix X X ℝ := Matrix.of fun x x' => M.P x (σ x) x'

/-- `P_σ` is Markov. -/
theorem isMarkov_Pσ (σ : X → A) : IsMarkov (M.Pσ σ) :=
  ⟨fun x x' => M.P_nonneg x (σ x) x', fun x => M.P_rowsum x (σ x)⟩

/-- The reward `r_σ(x) = r(x, σ(x))`. -/
def rσ (σ : X → A) : X → ℝ := fun x => M.r x (σ x)

/-- The RDP of an MDP (Example 8.1.1, restated): `V = ℝ^X`,
`B(x, a, v) = r(x, a) + β ∑ v(x')P(x, a, x')`. -/
def toRDP : RDP X A where
  Γ := M.Γ
  Γ_nonempty := M.Γ_nonempty
  V := univ
  B := fun x a v => M.r x a + M.β * ∑ x', v x' * M.P x a x'
  mono := fun x a _ _ _ _ _ hvw => add_le_add le_rfl (mul_le_mul_of_nonneg_left
    (sum_le_sum fun x' _ => mul_le_mul_of_nonneg_right (hvw x') (M.P_nonneg x a x')) M.β_pos.le)
  consistent := fun _ _ _ _ => mem_univ _

/-- The policy operators are `T_σ v = r_σ + βP_σ v` (5.19). -/
theorem toRDP_Tσ (σ : X → A) (v : X → ℝ) :
    M.toRDP.Tσ σ v = affineOp (M.β • M.Pσ σ) (M.rσ σ) v := by
  funext x
  simp only [RDP.Tσ, toRDP, affineOp, Pi.add_apply, mulVec, dotProduct, Matrix.smul_apply,
    smul_eq_mul, Pσ, Matrix.of_apply, rσ, Finset.mul_sum]
  rw [add_comm]
  congr 1
  exact sum_congr rfl fun x' _ => by ring

/-- **Example 9.1.2** (p. 295): the ADP `A_M` generated by an MDP. -/
noncomputable def toADP : ADP M.toRDP.V M.toRDP.Policy := M.toRDP.toADP

/-- Each `T_σ` of an MDP is globally stable on `ℝ^X`. -/
theorem toRDP_isGloballyStable [Nonempty X] : M.toRDP.IsGloballyStable := by
  classical
  intro σ _
  have hρ : specRad (M.β • M.Pσ σ) < 1 := by
    rw [specRad_smul_isMarkov (M.isMarkov_Pσ σ) M.β_pos.le]
    exact M.β_lt_one
  have hT : M.toRDP.Tσ σ = affineOp (M.β • M.Pσ σ) (M.rσ σ) := funext (M.toRDP_Tσ σ)
  change GloballyStableOn (M.toRDP.Tσ σ) univ
  rw [hT, globallyStableOn_univ_iff]
  exact globallyStable_affineOp hρ _

/-- **Example 9.2.1** (p. 297): the `σ`-value functions of `A_M` are `v_σ = (I − βP_σ)⁻¹r_σ`. -/
theorem toADP_vσ [DecidableEq X] [Nonempty X] (hw : M.toADP.WellPosed) (σ : M.toRDP.Policy) :
    (M.toADP.vσ hw σ : X → ℝ) = (1 - M.β • M.Pσ σ.1)⁻¹ *ᵥ M.rσ σ.1 := by
  have hρ : specRad (M.β • M.Pσ σ.1) < 1 := by
    rw [specRad_smul_isMarkov (M.isMarkov_Pσ σ.1) M.β_pos.le]
    exact M.β_lt_one
  have hfix := isFixedPt_affineOp_inv hρ (M.rσ σ.1)
  have h := ADP.eq_vσ_of_isFixedPt hw (σ := σ)
    (v := ⟨(1 - M.β • M.Pσ σ.1)⁻¹ *ᵥ M.rσ σ.1, mem_univ _⟩) (Subtype.ext (by
      change M.toRDP.Tσ σ.1 _ = _
      rw [M.toRDP_Tσ]
      exact hfix))
  rw [← h]

end MDP

/-! ### Q-factors (Examples 9.1.3–9.1.4, Exercise 9.2.2) -/

/-- The entropic aggregate `θ⁻¹ ln ∑ exp(θ g(x'))p(x')` is increasing in `g` for a distribution
`p` and `θ ≠ 0`. -/
theorem entropic_mono {X : Type*} [Fintype X] {p : X → ℝ} (hp0 : ∀ x', 0 ≤ p x')
    (hp1 : ∑ x', p x' = 1) {θ : ℝ} (hθ : θ ≠ 0) {g h : X → ℝ} (hgh : g ≤ h) :
    θ⁻¹ * Real.log (∑ x', Real.exp (θ * g x') * p x') ≤
      θ⁻¹ * Real.log (∑ x', Real.exp (θ * h x') * p x') := by
  have hpos : ∀ f : X → ℝ, 0 < ∑ x', Real.exp (θ * f x') * p x' := fun f => by
    obtain ⟨x, hx⟩ : ∃ x, 0 < p x := by
      by_contra hcon
      simp only [not_exists, not_lt] at hcon
      have : ∑ x', p x' ≤ 0 := sum_nonpos fun x' _ => hcon x'
      linarith
    exact lt_of_lt_of_le (mul_pos (Real.exp_pos _) hx) (single_le_sum
      (f := fun x' => Real.exp (θ * f x') * p x')
      (fun y _ => mul_nonneg (Real.exp_pos _).le (hp0 y)) (mem_univ x))
  rcases lt_or_gt_of_ne hθ with hneg | hpos'
  · have hs : ∑ x', Real.exp (θ * h x') * p x' ≤ ∑ x', Real.exp (θ * g x') * p x' :=
      sum_le_sum fun x' _ => mul_le_mul_of_nonneg_right
        (Real.exp_le_exp.2 (mul_le_mul_of_nonpos_left (hgh x') hneg.le)) (hp0 x')
    exact mul_le_mul_of_nonpos_left (Real.log_le_log (hpos h) hs) (inv_nonpos.2 hneg.le)
  · have hs : ∑ x', Real.exp (θ * g x') * p x' ≤ ∑ x', Real.exp (θ * h x') * p x' :=
      sum_le_sum fun x' _ => mul_le_mul_of_nonneg_right
        (Real.exp_le_exp.2 (mul_le_mul_of_nonneg_left (hgh x') hpos'.le)) (hp0 x')
    exact mul_le_mul_of_nonneg_left (Real.log_le_log (hpos g) hs) (inv_nonneg.2 hpos'.le)


namespace MDP

variable {X A : Type*} [Fintype X] [Fintype A] (M : MDP X A)

/-- The Q-factor policy operators (9.2): `(S_σ q)(x, a) = r(x, a) + β ∑ q(x', σ(x'))P(x, a, x')`,
on `ℝ^{X × A}` (the values off `G` are carried along and never used). -/
def qOp (σ : X → A) (q : X → A → ℝ) : X → A → ℝ :=
  fun x a => M.r x a + M.β * ∑ x', q x' (σ x') * M.P x a x'

/-- A policy maximising `q(x, ·)` over `Γ(x)`. -/
noncomputable def qGreedy (q : X → A → ℝ) : M.toRDP.Policy :=
  ⟨fun x => ((M.Γ x).exists_max_image (q x) (M.Γ_nonempty x)).choose,
    fun x => ((M.Γ x).exists_max_image (q x) (M.Γ_nonempty x)).choose_spec.1⟩

/-- A policy minimising `q(x, ·)` over `Γ(x)`. -/
noncomputable def qMinGreedy (q : X → A → ℝ) : M.toRDP.Policy :=
  ⟨fun x => ((M.Γ x).exists_min_image (q x) (M.Γ_nonempty x)).choose,
    fun x => ((M.Γ x).exists_min_image (q x) (M.Γ_nonempty x)).choose_spec.1⟩

theorem qOp_mono {σ τ : X → A} {q : X → A → ℝ} (h : ∀ x', q x' (τ x') ≤ q x' (σ x')) :
    M.qOp τ q ≤ M.qOp σ q := fun x a =>
  add_le_add le_rfl (mul_le_mul_of_nonneg_left (sum_le_sum fun x' _ =>
    mul_le_mul_of_nonneg_right (h x') (M.P_nonneg x a x')) M.β_pos.le)

/-- **Example 9.1.3** (p. 296): the Q-factor operators `{S_σ}` form an ADP on `ℝ^{X × A}`. -/
noncomputable def qADP : ADP (X → A → ℝ) M.toRDP.Policy where
  T σ q := M.qOp σ.1 q
  exists_greedy q := ⟨M.qGreedy q, fun τ => M.qOp_mono fun x' =>
    ((M.Γ x').exists_max_image (q x') (M.Γ_nonempty x')).choose_spec.2 _ (τ.2 x')⟩
  exists_minGreedy q := ⟨M.qMinGreedy q, fun τ => M.qOp_mono fun x' =>
    ((M.Γ x').exists_min_image (q x') (M.Γ_nonempty x')).choose_spec.2 _ (τ.2 x')⟩

/-- Each Q-factor policy operator is a contraction of modulus `β` on `ℝ^{X × A}`. -/
theorem qOp_isContractionOn (σ : X → A) : IsContractionOn (M.qOp σ) univ M.β := by
  refine ⟨mapsTo_univ _ _, M.β_pos.le, M.β_lt_one, fun q _ q' _ => ?_⟩
  have hq : ∀ x', |q x' (σ x') - q' x' (σ x')| ≤ ‖q - q'‖ := fun x' => by
    rw [← Real.norm_eq_abs]
    exact (norm_le_pi_norm ((q - q') x') (σ x')).trans (norm_le_pi_norm (q - q') x')
  refine (pi_norm_le_iff_of_nonneg (mul_nonneg M.β_pos.le (norm_nonneg _))).2 fun x => ?_
  refine (pi_norm_le_iff_of_nonneg (mul_nonneg M.β_pos.le (norm_nonneg _))).2 fun a => ?_
  simp only [Pi.sub_apply, qOp, Real.norm_eq_abs, add_sub_add_left_eq_sub, ← mul_sub,
    ← sum_sub_distrib, ← sub_mul, abs_mul, abs_of_pos M.β_pos]
  refine mul_le_mul_of_nonneg_left ((abs_sum_le_sum_abs _ _).trans ?_) M.β_pos.le
  calc ∑ x', |(q x' (σ x') - q' x' (σ x')) * M.P x a x'| ≤ ∑ x', ‖q - q'‖ * M.P x a x' :=
        sum_le_sum fun x' _ => by
          rw [abs_mul, abs_of_nonneg (M.P_nonneg x a x')]
          exact mul_le_mul_of_nonneg_right (hq x') (M.P_nonneg x a x')
    _ = ‖q - q'‖ := by rw [← Finset.mul_sum, M.P_rowsum, mul_one]

/-- **Exercise 9.2.2** (p. 299): the Q-factor ADP is max-stable. -/
theorem qADP_isMaxStable : M.qADP.IsMaxStable := by
  have := M.toRDP.policy_nonempty
  refine ADP.IsOrderStable.isMaxStable fun σ => ?_
  refine orderStable_of_globallyStable (fun q q' hqq' => M.qOp_mono (q := q) (τ := σ.1)
    (σ := σ.1) (fun _ => le_rfl) |>.trans ?_) (M.qOp_isContractionOn σ.1).globallyStable_univ
  intro x a
  exact add_le_add le_rfl (mul_le_mul_of_nonneg_left (sum_le_sum fun x' _ =>
    mul_le_mul_of_nonneg_right (hqq' x' (σ.1 x')) (M.P_nonneg x a x')) M.β_pos.le)

/-- The risk-sensitive Q-factor policy operators (9.4):
`(Q_σ f)(x, a) = r(x, a) + (β/θ) ln ∑ exp[θf(x', σ(x'))]P(x, a, x')`. -/
noncomputable def rsqOp (θ : ℝ) (σ : X → A) (f : X → A → ℝ) : X → A → ℝ :=
  fun x a => M.r x a + M.β * (θ⁻¹ * Real.log (∑ x', Real.exp (θ * f x' (σ x')) * M.P x a x'))

theorem rsqOp_mono {θ : ℝ} (hθ : θ ≠ 0) {σ τ : X → A} {f : X → A → ℝ}
    (h : ∀ x', f x' (τ x') ≤ f x' (σ x')) : M.rsqOp θ τ f ≤ M.rsqOp θ σ f := fun x a =>
  add_le_add le_rfl (mul_le_mul_of_nonneg_left (entropic_mono (M.P_nonneg x a)
    (M.P_rowsum x a) hθ (g := fun x' => f x' (τ x')) (h := fun x' => f x' (σ x')) h)
    M.β_pos.le)

/-- **Example 9.1.4** (p. 296): the risk-sensitive Q-factor operators form an ADP on
`ℝ^{X × A}`. -/
noncomputable def rsqADP {θ : ℝ} (hθ : θ ≠ 0) : ADP (X → A → ℝ) M.toRDP.Policy where
  T σ f := M.rsqOp θ σ.1 f
  exists_greedy f := ⟨M.qGreedy f, fun τ => M.rsqOp_mono hθ fun x' =>
    ((M.Γ x').exists_max_image (f x') (M.Γ_nonempty x')).choose_spec.2 _ (τ.2 x')⟩
  exists_minGreedy f := ⟨M.qMinGreedy f, fun τ => M.rsqOp_mono hθ fun x' =>
    ((M.Γ x').exists_min_image (f x') (M.Γ_nonempty x')).choose_spec.2 _ (τ.2 x')⟩

end MDP

end SargentStachurski.AbstractDynamicProgramming
