/-
Copyright (c) 2026 Robert Kirkby. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Robert Kirkby
-/
import AbstractDynamicProgramming.Examples

/-!
# Optimality results for RDPs via ADPs

Sargent and Stachurski, *Dynamic Programming*, Volume 1, §9.2.2 (pp. 302–304): the proofs of
Theorems 8.1.1 and 8.1.2 through the ADP generated by an RDP.

* Translation: when `A_R` is order stable, Theorem 9.2.4 for `A_R` gives, for `R`, that `v*` is
  the unique solution of the Bellman equation in `V`, Bellman's principle of optimality, the
  existence of an optimal policy and finite termination of HPI.
* OPI: Lemma 9.2.6 (`Tᵏv → v*` from `v ∈ V_Σ`), Lemma 9.2.7 (`W_m` maps `V_u` into itself and
  `Tv ≼ W_m v ≼ Tᵐv`), Lemma 9.2.8 (`Tᵏv ≼ W_mᵏv`), Lemma 9.2.9 (if OPI repeats a value it has
  found `v*`) and Lemma 9.2.10 (along a sequence in `V_u` converging to `v*`, greedy policies are
  eventually optimal).
* **Theorem 8.1.1** for globally stable RDPs, (i)–(v).
* Bounded RDPs (Exercises 8.1.12–8.1.13, restated) and **Theorem 8.1.2**, through
  Proposition 9.2.3 on the reduced RDP `(Γ, [v₁, v₂], B)`.
-/

open Finset Matrix Filter Topology Function Set

namespace SargentStachurski.AbstractDynamicProgramming

namespace RDP

variable {X A : Type*} [Fintype X] [Fintype A] {R : RDP X A}

/-- Upward stability of `T_σ` around `v_σ`, from order stability of `A_R`. -/
theorem le_vσ_of_le_Tσ (hw : R.WellPosed) (hs : R.toADP.IsOrderStable) {σ : X → A}
    (hσ : R.IsFeasible σ) {v : X → ℝ} (hv : v ∈ R.V) (h : v ≤ R.Tσ σ v) : v ≤ R.vσ σ := by
  have := hs.le_vσ (σ := ⟨σ, hσ⟩) (v := ⟨v, hv⟩) h
  have e := toADP_vσ hw hs.wellPosed ⟨σ, hσ⟩
  change v ≤ (R.toADP.vσ hs.wellPosed ⟨σ, hσ⟩ : X → ℝ) at this
  rwa [e] at this

/-- Downward stability of `T_σ` around `v_σ`, from order stability of `A_R`. -/
theorem vσ_le_of_Tσ_le (hw : R.WellPosed) (hs : R.toADP.IsOrderStable) {σ : X → A}
    (hσ : R.IsFeasible σ) {v : X → ℝ} (hv : v ∈ R.V) (h : R.Tσ σ v ≤ v) : R.vσ σ ≤ v := by
  have := hs.vσ_le (σ := ⟨σ, hσ⟩) (v := ⟨v, hv⟩) h
  have e := toADP_vσ hw hs.wellPosed ⟨σ, hσ⟩
  change (R.toADP.vσ hs.wellPosed ⟨σ, hσ⟩ : X → ℝ) ≤ v at this
  rwa [e] at this

variable [DecidableEq X] [DecidableEq A]

/-- Theorem 9.2.4 for `A_R`, translated to `R`: if `R` is well-posed and `A_R` is order stable,
then `v*` is the unique solution of the Bellman equation in `V`, Bellman's principle of optimality
holds, an optimal policy exists, and HPI (on `A_R`) returns an optimal policy in finitely many
steps. -/
theorem optimality_of_orderStable (hw : R.WellPosed) (hs : R.toADP.IsOrderStable) :
    (R.vstar ∈ R.V ∧ IsFixedPt R.T R.vstar ∧ ∀ v ∈ R.V, IsFixedPt R.T v → v = R.vstar) ∧
      (∀ σ, R.IsFeasible σ → (R.IsOptimal σ ↔ R.IsGreedy R.vstar σ)) ∧
      (∃ σ, R.IsOptimal σ) ∧
      ∀ σ₀ : R.Policy, ∃ k, R.toADP.hpiValue hs.wellPosed σ₀ (k + 1) =
        R.toADP.hpiValue hs.wellPosed σ₀ k ∧
        R.IsOptimal (R.toADP.hpiPolicy hs.wellPosed σ₀ (k + 1)).1 := by
  have := R.policy_nonempty
  obtain ⟨w, hgr, hfixiff, hprin, ⟨σ0, hσ0⟩, hhpi⟩ := hs.maxOptimality
  have hv : ∀ σ : R.Policy, (R.toADP.vσ hs.wellPosed σ : X → ℝ) = R.vσ σ.1 :=
    toADP_vσ hw hs.wellPosed
  have hwv : (w : X → ℝ) = R.vstar := by
    obtain ⟨σw, hσw⟩ := hgr.1
    funext x
    refine le_antisymm ?_ (Finset.sup'_le _ _ fun τ _ => ?_)
    · rw [← hσw, hv]
      exact R.vσ_le_vstar σw.2 x
    · rw [← hv]
      exact hgr.2 ⟨τ, rfl⟩ x
  have hopt : ∀ σ : R.Policy, R.toADP.IsOptimal hs.wellPosed σ ↔ R.IsOptimal σ.1 := by
    intro σ
    constructor
    · intro h
      refine ⟨σ.2, le_antisymm (R.vσ_le_vstar σ.2) fun x => ?_⟩
      refine Finset.sup'_le _ _ fun τ _ => ?_
      rw [← hv, ← hv]
      exact h τ x
    · intro h τ x
      rw [hv, hv, h.2]
      exact R.vσ_le_vstar τ.2 x
  have hfix : IsFixedPt R.T R.vstar := by
    have h1 := ((hfixiff w).2 rfl).eq
    have h2 := congrArg Subtype.val h1
    rw [toADP_bellman] at h2
    rw [← hwv]
    exact h2
  refine ⟨⟨hwv ▸ w.2, hfix, fun v hvV hvfix => ?_⟩, fun σ hσ => ?_, ?_, fun σ₀ => ?_⟩
  · have h1 : IsFixedPt R.toADP.bellman ⟨v, hvV⟩ :=
      Subtype.ext ((toADP_bellman R ⟨v, hvV⟩).trans hvfix.eq)
    rw [← hwv]
    exact congrArg Subtype.val ((hfixiff _).1 h1)
  · rw [← hopt ⟨σ, hσ⟩, hprin, ADP.isGreedy_iff, R.isGreedy_iff_Tσ_eq_T _ hσ, ← hwv]
    constructor
    · intro h
      have := congrArg Subtype.val h
      rwa [toADP_bellman] at this
    · intro h
      exact Subtype.ext (h.trans (toADP_bellman R w).symm)
  · exact ⟨σ0.1, (hopt σ0).1 hσ0⟩
  · obtain ⟨k, hk, hk'⟩ := hhpi σ₀
    exact ⟨k, hk, (hopt _).1 hk'⟩

/-! ### OPI (Lemmas 9.2.6–9.2.10) -/

/-- **Lemma 9.2.6** (p. 302): for globally stable `R` and `v ∈ V_Σ`, `Tᵏv → v*`. -/
theorem tendsto_iterate_T_vσ (hR : R.IsGloballyStable) {σ : X → A} (hσ : R.IsFeasible σ) :
    Tendsto (fun k : ℕ => R.T^[k] (R.vσ σ)) atTop (𝓝 R.vstar) := by
  have hw := hR.wellPosed
  obtain ⟨⟨hstar, hfix, -⟩, -, ⟨σs, hσs⟩, -⟩ :=
    optimality_of_orderStable hw (toADP_isOrderStable hR)
  have hv := vσ_mem hw hσ
  have hlow : ∀ k, (R.Tσ σs)^[k] (R.vσ σ) ≤ R.T^[k] (R.vσ σ) := by
    intro k
    induction k with
    | zero => simp
    | succ k ih =>
      rw [iterate_succ_apply', iterate_succ_apply']
      exact (R.Tσ_monotoneOn hσs.1 ((R.Tσ_mapsTo hσs.1).iterate k hv) (R.T_mapsTo.iterate k hv)
        ih).trans (R.Tσ_le_T hσs.1 _)
  have hup : ∀ k, R.T^[k] (R.vσ σ) ≤ R.vstar := fun k => by
    have := R.iterate_T_mono hv hstar (R.vσ_le_vstar hσ) k
    rwa [(hfix.iterate k).eq] at this
  have hlim := tendsto_iterate_Tσ hR hσs.1 hv
  rw [hσs.2] at hlim
  rw [tendsto_pi_nhds] at hlim ⊢
  intro x
  exact tendsto_of_tendsto_of_tendsto_of_le_of_le (hlim x) tendsto_const_nhds
    (fun k => hlow k x) (fun k => hup k x)

omit [DecidableEq X] [DecidableEq A] in
/-- `T_σᵐ v ≼ Tᵐ v` on `V` (Exercise 2.2.36). -/
theorem iterate_Tσ_le_iterate_T {σ : X → A} (hσ : R.IsFeasible σ) {v : X → ℝ} (hv : v ∈ R.V)
    (m : ℕ) : (R.Tσ σ)^[m] v ≤ R.T^[m] v := by
  induction m with
  | zero => exact le_rfl
  | succ m ih =>
    rw [iterate_succ_apply', iterate_succ_apply']
    exact (R.Tσ_le_T hσ _).trans (R.T_monotoneOn ((R.Tσ_mapsTo hσ).iterate m hv)
      (R.T_mapsTo.iterate m hv) ih)

omit [DecidableEq X] [DecidableEq A] in
/-- **Lemma 9.2.7** (p. 302): `W_m` maps `V_u = {v ∈ V : v ≼ Tv}` into itself, and
`Tv ≼ W_m v ≼ Tᵐv` for `v ∈ V_u` and `m ≥ 1`. -/
theorem opiW_spec {m : ℕ} (hm : 1 ≤ m) {v : X → ℝ} (hv : v ∈ R.V) (hvT : v ≤ R.T v) :
    R.opiW m v ∈ R.V ∧ R.opiW m v ≤ R.T (R.opiW m v) ∧ R.T v ≤ R.opiW m v ∧
      R.opiW m v ≤ R.T^[m] v := by
  set g := R.greedy v
  have hg := R.isGreedy_greedy v
  have hgv : v ≤ R.Tσ g v := by rw [R.Tσ_eq_T_of_isGreedy hg]; exact hvT
  have hmon : ∀ j, (R.Tσ g)^[j] v ≤ (R.Tσ g)^[j + 1] v := by
    intro j
    have := R.iterate_Tσ_mono hg.1 hv ((R.Tσ_mapsTo hg.1) hv) hgv j
    rwa [← iterate_succ_apply] at this
  have hge : ∀ j, R.Tσ g v ≤ (R.Tσ g)^[j + 1] v := by
    intro j
    induction j with
    | zero => simp
    | succ j ih => exact ih.trans (hmon (j + 1))
  obtain ⟨m', rfl⟩ : ∃ m', m = m' + 1 := ⟨m - 1, by omega⟩
  refine ⟨(R.Tσ_mapsTo hg.1).iterate _ hv, ?_, ?_, iterate_Tσ_le_iterate_T hg.1 hv _⟩
  · calc R.opiW (m' + 1) v = (R.Tσ g)^[m' + 1] v := rfl
      _ ≤ (R.Tσ g)^[m' + 1 + 1] v := hmon (m' + 1)
      _ = R.Tσ g ((R.Tσ g)^[m' + 1] v) := iterate_succ_apply' _ _ _
      _ ≤ R.T ((R.Tσ g)^[m' + 1] v) := R.Tσ_le_T hg.1 _
  · rw [← R.Tσ_eq_T_of_isGreedy hg]
    exact hge m'

omit [DecidableEq X] [DecidableEq A] in
/-- **Lemma 9.2.8** (p. 303): for `v ∈ V_u`, `Tᵏv ≼ W_mᵏv`, and the OPI iterates stay in `V_u`. -/
theorem iterate_T_le_opi {m : ℕ} (hm : 1 ≤ m) {v : X → ℝ} (hv : v ∈ R.V) (hvT : v ≤ R.T v)
    (k : ℕ) : (R.opiW m)^[k] v ∈ R.V ∧ (R.opiW m)^[k] v ≤ R.T ((R.opiW m)^[k] v) ∧
      R.T^[k] v ≤ (R.opiW m)^[k] v := by
  induction k with
  | zero => exact ⟨hv, hvT, le_rfl⟩
  | succ k ih =>
    obtain ⟨h1, h2, h3⟩ := ih
    obtain ⟨g1, g2, g3, -⟩ := opiW_spec hm h1 h2
    rw [iterate_succ_apply', iterate_succ_apply']
    exact ⟨g1, g2, (R.T_monotoneOn (R.T_mapsTo.iterate k hv) h1 h3).trans g3⟩

/-- **Lemma 9.2.9** (p. 303): for globally stable `R`, `v₀ ∈ V_Σ` and `vₖ = W_mᵏv₀`, if
`vₖ = vₖ₊₁` then `vₖ = v*` and every `vₖ`-greedy policy is optimal. -/
theorem opi_stop (hR : R.IsGloballyStable) {m : ℕ} (hm : 1 ≤ m) {σ₀ : X → A}
    (hσ₀ : R.IsFeasible σ₀) {k : ℕ} (hk : R.opiValue m σ₀ (k + 1) = R.opiValue m σ₀ k) :
    R.opiValue m σ₀ k = R.vstar ∧ ∀ σ, R.IsGreedy (R.opiValue m σ₀ k) σ → R.IsOptimal σ := by
  have hw := hR.wellPosed
  obtain ⟨⟨-, -, huniq⟩, hprin, -, -⟩ := optimality_of_orderStable hw (toADP_isOrderStable hR)
  have hv0 := vσ_mem hw hσ₀
  have hv0T : R.vσ σ₀ ≤ R.T (R.vσ σ₀) :=
    (isFixedPt_vσ hw hσ₀).eq.symm.le.trans (R.Tσ_le_T hσ₀ _)
  obtain ⟨h1, h2, -⟩ := iterate_T_le_opi hm hv0 hv0T k
  set v := R.opiValue m σ₀ k
  obtain ⟨-, -, g3, g4⟩ := opiW_spec hm h1 h2
  have hW : R.opiW m v = v := by
    have : R.opiValue m σ₀ (k + 1) = R.opiW m v := iterate_succ_apply' _ _ _
    rw [← this, hk]
  -- `v ≼ Tv ≼ W_m v = v`
  have hfix : IsFixedPt R.T v := le_antisymm (g3.trans_eq hW) h2
  have hvstar := huniq v h1 hfix
  refine ⟨hvstar, fun σ hσ => ?_⟩
  rw [hvstar] at hσ
  exact (hprin σ hσ.1).2 hσ

/-- **Lemma 9.2.10** (p. 303): for globally stable `R`, if `(vₖ) ⊆ V_u` and `vₖ → v*`, then from
some `K` on every `vₖ`-greedy policy is optimal. -/
theorem eventually_optimal (hR : R.IsGloballyStable) {vs : ℕ → X → ℝ}
    (hvs : ∀ k, vs k ∈ R.V ∧ vs k ≤ R.T (vs k)) (hlim : Tendsto vs atTop (𝓝 R.vstar)) :
    ∃ K, ∀ k ≥ K, ∀ σ, R.IsGreedy (vs k) σ → R.IsOptimal σ := by
  have hw := hR.wellPosed
  have hs := toADP_isOrderStable hR
  have hgap : ∀ τ : R.Policy, ∀ᶠ k in atTop,
      ¬ R.IsOptimal τ.1 → ∃ x, R.vσ τ.1 x < vs k x := by
    intro τ
    by_cases hopt : R.IsOptimal τ.1
    · exact Eventually.of_forall fun _ h => absurd hopt h
    · have hlt : ∃ x, R.vσ τ.1 x < R.vstar x := by
        by_contra hcon
        exact hopt ⟨τ.2, le_antisymm (R.vσ_le_vstar τ.2) fun x => not_lt.1 fun h => hcon ⟨x, h⟩⟩
      obtain ⟨x, hx⟩ := hlt
      filter_upwards [(tendsto_pi_nhds.1 hlim x).eventually (lt_mem_nhds hx)] with k hk _
      exact ⟨x, hk⟩
  obtain ⟨K, hK⟩ := eventually_atTop.1 (eventually_all.2 hgap)
  refine ⟨K, fun k hk σ hσ => ?_⟩
  by_contra hnot
  obtain ⟨x, hx⟩ := hK k hk ⟨σ, hσ.1⟩ hnot
  have hle : vs k ≤ R.vσ σ := le_vσ_of_le_Tσ hw hs hσ.1 (hvs k).1
    ((hvs k).2.trans_eq (R.Tσ_eq_T_of_isGreedy hσ).symm)
  exact absurd (hle x) (not_le.2 hx)

/-- **Theorem 8.1.1** (p. 257), proved as in §9.2.2.2: for a globally stable RDP, (i) `v*` is the
unique solution of the Bellman equation in `V`, (ii) Bellman's principle of optimality holds,
(iii) an optimal policy exists, (iv) HPI returns an optimal policy in finitely many steps, and
(v) for every `m ≥ 1` and `v₀ = v_σ` the OPI values converge to `v*` and the greedy policies `σₖ`
are optimal from some `K` on. -/
theorem optimality_of_globallyStable (hR : R.IsGloballyStable) :
    (R.vstar ∈ R.V ∧ IsFixedPt R.T R.vstar ∧ ∀ v ∈ R.V, IsFixedPt R.T v → v = R.vstar) ∧
      (∀ σ, R.IsFeasible σ → (R.IsOptimal σ ↔ R.IsGreedy R.vstar σ)) ∧
      (∃ σ, R.IsOptimal σ) ∧
      (∀ σ₀ : R.Policy, ∃ k, R.toADP.hpiValue (toADP_isOrderStable hR).wellPosed σ₀ (k + 1) =
        R.toADP.hpiValue (toADP_isOrderStable hR).wellPosed σ₀ k ∧
        R.IsOptimal (R.toADP.hpiPolicy (toADP_isOrderStable hR).wellPosed σ₀ (k + 1)).1) ∧
      ∀ m, 1 ≤ m → ∀ σ, R.IsFeasible σ → Tendsto (R.opiValue m σ) atTop (𝓝 R.vstar) ∧
        ∃ K, ∀ k ≥ K, R.IsOptimal (R.greedy (R.opiValue m σ k)) := by
  have hw := hR.wellPosed
  obtain ⟨h1, h2, h3, h4⟩ := optimality_of_orderStable hw (toADP_isOrderStable hR)
  refine ⟨h1, h2, h3, h4, fun m hm σ hσ => ?_⟩
  obtain ⟨hstar, hfix, -⟩ := h1
  have hv0 := vσ_mem hw hσ
  have hv0T : R.vσ σ ≤ R.T (R.vσ σ) :=
    (isFixedPt_vσ hw hσ).eq.symm.le.trans (R.Tσ_le_T hσ _)
  have hspec := iterate_T_le_opi hm hv0 hv0T
  -- `W_m` preserves `≼ v*`
  have hWup : ∀ w ∈ R.V, w ≤ R.vstar → R.opiW m w ≤ R.vstar := fun w hwV hw' => by
    have hg := R.isGreedy_greedy w
    have hk : ∀ j, (R.Tσ (R.greedy w))^[j] w ≤ R.vstar := by
      intro j
      induction j with
      | zero => exact hw'
      | succ j ih =>
        rw [iterate_succ_apply']
        exact (R.Tσ_le_T hg.1 _).trans ((R.T_monotoneOn ((R.Tσ_mapsTo hg.1).iterate j hwV) hstar
          ih).trans hfix.eq.le)
    exact hk m
  have hup : ∀ k, R.opiValue m σ k ≤ R.vstar := by
    intro k
    induction k with
    | zero => exact R.vσ_le_vstar hσ
    | succ k ih =>
      change (R.opiW m)^[k + 1] (R.vσ σ) ≤ R.vstar
      rw [iterate_succ_apply']
      exact hWup _ (hspec k).1 ih
  have hconv : Tendsto (R.opiValue m σ) atTop (𝓝 R.vstar) := by
    have hlim := tendsto_iterate_T_vσ hR hσ
    rw [tendsto_pi_nhds] at hlim ⊢
    intro x
    exact tendsto_of_tendsto_of_tendsto_of_le_of_le (hlim x) tendsto_const_nhds
      (fun k => (hspec k).2.2 x) (fun k => hup k x)
  obtain ⟨K, hK⟩ := eventually_optimal hR (fun k => ⟨(hspec k).1, (hspec k).2.1⟩) hconv
  exact ⟨hconv, K, fun k hk => hK k hk _ (R.isGreedy_greedy _)⟩

/-! ### Bounded RDPs and Theorem 8.1.2 -/

omit [DecidableEq X] [DecidableEq A] in
/-- `R` is bounded by `v₁ ≤ v₂` (§8.1.3.6, restated): `[v₁, v₂] ⊆ V` and (8.20). -/
def IsBoundedBy (R : RDP X A) (v₁ v₂ : X → ℝ) : Prop :=
  v₁ ≤ v₂ ∧ Icc v₁ v₂ ⊆ R.V ∧ ∀ x, ∀ a ∈ R.Γ x, v₁ x ≤ R.B x a v₁ ∧ R.B x a v₂ ≤ v₂ x

omit [DecidableEq X] [DecidableEq A] in
/-- Policy operators of a bounded RDP map `[v₁, v₂]` into itself. -/
theorem Tσ_mapsTo_Icc {v₁ v₂ : X → ℝ} (hb : R.IsBoundedBy v₁ v₂) {σ : X → A}
    (hσ : R.IsFeasible σ) : MapsTo (R.Tσ σ) (Icc v₁ v₂) (Icc v₁ v₂) := by
  intro v hv
  have h1 : v₁ ∈ R.V := hb.2.1 ⟨le_rfl, hb.1⟩
  have h2 : v₂ ∈ R.V := hb.2.1 ⟨hb.1, le_rfl⟩
  exact ⟨fun x => (hb.2.2 x _ (hσ x)).1.trans (R.mono x _ (hσ x) v₁ h1 v (hb.2.1 hv) hv.1),
    fun x => (R.mono x _ (hσ x) v (hb.2.1 hv) v₂ h2 hv.2).trans (hb.2.2 x _ (hσ x)).2⟩

omit [DecidableEq X] [DecidableEq A] in
/-- Exercise 8.1.12 (p. 259, restated): the reduced RDP `(Γ, [v₁, v₂], B)`. -/
def restrictIcc {v₁ v₂ : X → ℝ} (hb : R.IsBoundedBy v₁ v₂) : RDP X A where
  Γ := R.Γ
  Γ_nonempty := R.Γ_nonempty
  V := Icc v₁ v₂
  B := R.B
  mono := fun x a ha v hv w hw hvw => R.mono x a ha v (hb.2.1 hv) w (hb.2.1 hw) hvw
  consistent := fun _ hσ _ hv => Tσ_mapsTo_Icc hb hσ hv

omit [DecidableEq X] [DecidableEq A] in
/-- Exercise 8.1.13 (p. 259, restated): in a well-posed bounded RDP, `v_σ ∈ [v₁, v₂]`. -/
theorem vσ_mem_Icc (hw : R.WellPosed) {v₁ v₂ : X → ℝ} (hb : R.IsBoundedBy v₁ v₂) {σ : X → A}
    (hσ : R.IsFeasible σ) : R.vσ σ ∈ Icc v₁ v₂ := by
  have hmono : MonotoneOn (R.Tσ σ) (Icc v₁ v₂) := (R.Tσ_monotoneOn hσ).mono hb.2.1
  obtain ⟨z, hz, -, -, hzfix, -⟩ := knaster_tarski hb.1 (Tσ_mapsTo_Icc hb hσ) hmono
  rw [← eq_vσ_of_isFixedPt hw hσ (hb.2.1 hz) hzfix]
  exact hz

omit [DecidableEq X] [DecidableEq A] in
/-- The reduced RDP is well-posed, with the same `σ`-value functions. -/
theorem restrictIcc_wellPosed (hw : R.WellPosed) {v₁ v₂ : X → ℝ} (hb : R.IsBoundedBy v₁ v₂) :
    (R.restrictIcc hb).WellPosed ∧ ∀ σ, R.IsFeasible σ → (R.restrictIcc hb).vσ σ = R.vσ σ := by
  have hw' : (R.restrictIcc hb).WellPosed := fun σ hσ =>
    ⟨R.vσ σ, ⟨vσ_mem_Icc hw hb hσ, isFixedPt_vσ hw hσ⟩, fun w ⟨hwI, hwfix⟩ =>
      eq_vσ_of_isFixedPt hw hσ (hb.2.1 hwI) hwfix⟩
  exact ⟨hw', fun σ hσ => (eq_vσ_of_isFixedPt hw' hσ (vσ_mem_Icc hw hb hσ)
    (isFixedPt_vσ hw hσ)).symm⟩

/-- **Theorem 8.1.2** (p. 260), proved as in §9.2.2.2: for a well-posed RDP bounded by `v₁ ≤ v₂`,
(i) `v*` is the unique solution of the Bellman equation in `V`, (ii) Bellman's principle of
optimality holds, (iii) an optimal policy exists, and (iv) HPI on the reduced RDP returns an
optimal policy in finitely many steps. -/
theorem optimality_of_bounded (hw : R.WellPosed) {v₁ v₂ : X → ℝ} (hb : R.IsBoundedBy v₁ v₂) :
    (R.vstar ∈ R.V ∧ IsFixedPt R.T R.vstar ∧ ∀ v ∈ R.V, IsFixedPt R.T v → v = R.vstar) ∧
      (∀ σ, R.IsFeasible σ → (R.IsOptimal σ ↔ R.IsGreedy R.vstar σ)) ∧
      (∃ σ, R.IsOptimal σ) ∧
      ∃ hs : (R.restrictIcc hb).toADP.IsOrderStable, ∀ σ₀ : (R.restrictIcc hb).Policy,
        ∃ k, (R.restrictIcc hb).toADP.hpiValue hs.wellPosed σ₀ (k + 1) =
          (R.restrictIcc hb).toADP.hpiValue hs.wellPosed σ₀ k ∧
          R.IsOptimal ((R.restrictIcc hb).toADP.hpiPolicy hs.wellPosed σ₀ (k + 1)).1 := by
  set Rb := R.restrictIcc hb
  obtain ⟨hwb, hvb⟩ := restrictIcc_wellPosed hw hb
  have hsb : Rb.toADP.IsOrderStable := (toADP_wellPosed_iff hb.1 rfl).1 (toADP_wellPosed hwb)
  obtain ⟨⟨hmem, hfix, huniq⟩, hprin, ⟨σs, hσs⟩, hhpi⟩ := optimality_of_orderStable hwb hsb
  have hvstar : Rb.vstar = R.vstar := by
    funext x
    refine le_antisymm (Finset.sup'_le _ _ fun τ _ => ?_) (Finset.sup'_le _ _ fun τ _ => ?_)
    · rw [hvb τ.1 τ.2]
      exact R.vσ_le_vstar τ.2 x
    · rw [← hvb τ.1 τ.2]
      exact Rb.vσ_le_vstar τ.2 x
  have hopt : ∀ σ, R.IsFeasible σ → (Rb.IsOptimal σ ↔ R.IsOptimal σ) := fun σ hσ =>
    ⟨fun h => ⟨hσ, (hvb σ hσ).symm.trans (h.2.trans hvstar)⟩,
      fun h => ⟨h.1, (hvb σ hσ).trans (h.2.trans hvstar.symm)⟩⟩
  rw [hvstar] at hmem hfix huniq
  refine ⟨⟨hb.2.1 hmem, hfix, fun v hv hvfix => ?_⟩, fun σ hσ => ?_,
    ⟨σs, (hopt σs hσs.1).1 hσs⟩, hsb, fun σ₀ => ?_⟩
  · -- a fixed point of `T` in `V` is the value of its greedy policy, so it lies in `[v₁, v₂]`
    have hg := R.isGreedy_greedy v
    have hvg : v = R.vσ (R.greedy v) := eq_vσ_of_isFixedPt hw hg.1 hv (by
      change R.Tσ (R.greedy v) v = v
      rw [R.Tσ_eq_T_of_isGreedy hg, hvfix.eq])
    have hvI : v ∈ Icc v₁ v₂ := hvg ▸ vσ_mem_Icc hw hb hg.1
    exact huniq v hvI hvfix
  · rw [← hopt σ hσ, hprin σ hσ, hvstar]
    rfl
  · obtain ⟨k, hk, hk'⟩ := hhpi σ₀
    exact ⟨k, hk, (hopt _ (Rb.toADP.hpiPolicy hsb.wellPosed σ₀ (k + 1)).2).1 hk'⟩

end RDP

end SargentStachurski.AbstractDynamicProgramming
