/-
Copyright (c) 2026 Robert Kirkby. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Robert Kirkby
-/
import AdditionalApplications.BMOperators
import AdditionalApplications.Pospace
import Mathlib.Probability.Kernel.Composition.MapComap

/-!
# Linear decision processes

Sargent and Stachurski, *Dynamic Programming*, Volume 2, §6.1.2 (pp. 187–192).

A linear decision process `(Γ, r, K)` has a feasible correspondence `Γ`, a bounded measurable
reward `r` and a transition kernel `K` with `Kv ∈ bG` for `v ∈ bX`. Here `K` is written
`K(x, a, dx') = β(x, a)P(x, a, dx')` with `β ≥ 0` bounded measurable and `P` stochastic, which is
how every kernel in the chapter is built.

* Feasible policies are measurable selections of `Γ`; the policy operators (6.4) are
  `T_σ v = r_σ + K_σ v` on `bX`, with `K_σ` a positive bounded linear operator, so `(bX, 𝕋_LDP)` is
  an additive ADP (§6.1.2.2).
* (6.5)–(6.6): if `ρ(K_σ) < 1`, then `v_σ = ∑_{t ≥ 0} K_σ^t r_σ`, as the limit of partial sums.
* (6.7): `σ` is `v`-greedy iff `r(x, τ(x)) + (Kv)(x, τ(x)) ≤ r(x, σ(x)) + (Kv)(x, σ(x))` for all
  feasible `τ` and all `x`.
* **Example 6.1.4**: the firm valuation problem with state-dependent discounting is an LDP.
* **Example 6.1.6**: a risk-sensitive MDP is not an LDP: its policy operators are not affine.
-/

open Set Function Filter Topology MeasureTheory ProbabilityTheory

namespace SargentStachurski.AdditionalApplications

attribute [local instance] BM.normedAddCommGroup BM.module BM.normedSpace BM.lattice
  BM.isOrderedAddMonoid BM.hasSolidNorm BM.completeSpace BM.posSMulMono

/-- A linear decision process `(Γ, r, K)` with `K(x, a, dx') = β(x, a)P(x, a, dx')` (§6.1.2.1). -/
structure LDP (X A : Type*) [MeasurableSpace X] [MeasurableSpace A] where
  /-- the feasible correspondence -/
  Γ : X → Set A
  /-- the reward -/
  r : BM (X × A)
  /-- the discount factor of the transition kernel -/
  β : BM (X × A)
  β_nonneg : 0 ≤ β
  /-- the stochastic part of the transition kernel -/
  P : Kernel (X × A) X
  [P_markov : IsMarkovKernel P]
  /-- a feasible policy exists -/
  exists_policy : ∃ σ : X → A, Measurable σ ∧ ∀ x, σ x ∈ Γ x

namespace LDP

attribute [local instance] LDP.P_markov

variable {X A : Type*} [MeasurableSpace X] [MeasurableSpace A] (M : LDP X A)

/-- Feasible policies: measurable `σ : X → A` with `σ(x) ∈ Γ(x)`. -/
def Policy : Type _ := {σ : X → A // Measurable σ ∧ ∀ x, σ x ∈ M.Γ x}

theorem nonempty_policy : Nonempty M.Policy :=
  ⟨⟨M.exists_policy.choose, M.exists_policy.choose_spec⟩⟩

theorem measurable_graph (σ : M.Policy) : Measurable fun x => (x, σ.1 x) :=
  measurable_id.prodMk σ.2.1

/-- Restriction of `f ∈ bG` along `x ↦ (x, σ(x))`. -/
def along (σ : M.Policy) (f : BM (X × A)) : BM X :=
  ⟨fun x => f.toFun (x, σ.1 x), f.measurable'.comp (M.measurable_graph σ),
    ⟨‖f‖, fun _ => BM.abs_le_norm f _⟩⟩

/-- `r_σ(x) = r(x, σ(x))`. -/
def rσ (σ : M.Policy) : BM X := M.along σ M.r

/-- `β_σ(x) = β(x, σ(x))`. -/
def βσ (σ : M.Policy) : BM X := M.along σ M.β

/-- `P_σ(x, dx') = P(x, σ(x), dx')`. -/
noncomputable abbrev Pσ (σ : M.Policy) : Kernel X X := M.P.comap _ (M.measurable_graph σ)

/-- `K_σ = β_σ P_σ`, `(K_σ v)(x) = β(x, σ(x)) ∫ v(x')P(x, σ(x), dx')`. -/
noncomputable def K (σ : M.Policy) : BM X →L[ℝ] BM X :=
  (BM.mulCLM (M.βσ σ)).comp (BM.markovCLM (M.Pσ σ))

theorem K_apply (σ : M.Policy) (v : BM X) (x : X) :
    (M.K σ v).toFun x = M.β.toFun (x, σ.1 x) * ∫ x', v.toFun x' ∂(M.P (x, σ.1 x)) := rfl

theorem K_isPositive (σ : M.Policy) : BanachLattice.IsPositiveOp (M.K σ) := fun v hv =>
  BM.mulCLM_isPositive (h := M.βσ σ) (fun x => M.β_nonneg (x, σ.1 x)) _
    (BM.markovCLM_isPositive (M.Pσ σ) v hv)

/-- `|∫ v dK(x, a)| ≤ ‖β‖‖v‖`: `K` maps `bX` into `bG`, and `‖K_σ‖ ≤ ‖β‖`. -/
theorem norm_K_le (σ : M.Policy) : ‖M.K σ‖ ≤ ‖M.β‖ := by
  refine ContinuousLinearMap.opNorm_le_bound _ (norm_nonneg _) fun v => ?_
  refine BM.norm_le (mul_nonneg (norm_nonneg _) (norm_nonneg _)) fun x => ?_
  rw [K_apply, abs_mul]
  exact mul_le_mul (BM.abs_le_norm M.β _) (abs_markovOp_le (M.Pσ σ) (BM.abs_le_norm v) x)
    (abs_nonneg _) (norm_nonneg _)

/-- The ADP `(bX, 𝕋_LDP)` generated by `(Γ, r, K)` (§6.1.2.2), with `T_σ v = r_σ + K_σ v`. -/
noncomputable def adp : ADP (BM X) M.Policy where
  T σ v := M.rσ σ + M.K σ v
  mono σ _ _ h := add_le_add le_rfl ((M.K_isPositive σ).mono h)
  nonempty := M.nonempty_policy

/-- The policy operator (6.4): `(T_σ v)(x) = r(x, σ(x)) + ∫ v(x')K(x, σ(x), dx')`. -/
theorem T_apply (σ : M.Policy) (v : BM X) (x : X) :
    (M.adp.T σ v).toFun x =
      M.r.toFun (x, σ.1 x) + M.β.toFun (x, σ.1 x) * ∫ x', v.toFun x' ∂(M.P (x, σ.1 x)) := rfl

/-- `T_σ` has the additive form of §4.1.2.3, with positive `K_σ`. -/
theorem isAdditive : BanachLattice.IsAdditive id M.adp M.rσ M.K :=
  ⟨M.K_isPositive, fun _ _ => rfl⟩

/-- The objective `r(x, a) + ∫ v(x')K(x, a, dx')`. -/
noncomputable def obj (v : BM X) (p : X × A) : ℝ :=
  M.r.toFun p + M.β.toFun p * ∫ x', v.toFun x' ∂(M.P p)

theorem T_apply_obj (σ : M.Policy) (v : BM X) (x : X) :
    (M.adp.T σ v).toFun x = M.obj v (x, σ.1 x) := rfl

/-- (6.7): `σ` is `v`-greedy iff `r(x, τ(x)) + ∫ v dK(x, τ(x)) ≤ r(x, σ(x)) + ∫ v dK(x, σ(x))` for
all feasible `τ` and all `x`. -/
theorem isGreedy_iff (v : BM X) (σ : M.Policy) :
    M.adp.IsGreedy v σ ↔ ∀ τ : M.Policy, ∀ x, M.obj v (x, τ.1 x) ≤ M.obj v (x, σ.1 x) :=
  Iff.rfl

/-- A policy maximizing the objective over `Γ(x)` at every `x` (6.8) is `v`-greedy. -/
theorem isGreedy_of_argmax (v : BM X) (σ : M.Policy)
    (h : ∀ x, ∀ a ∈ M.Γ x, M.obj v (x, a) ≤ M.obj v (x, σ.1 x)) : M.adp.IsGreedy v σ :=
  fun τ x => h x _ (τ.2.2 x)

/-- With measurable singletons, a `v`-greedy policy maximizes the objective over `Γ(x)` at every
`x` (6.8): change any policy at a single state. -/
theorem argmax_of_isGreedy [MeasurableSingletonClass X] (v : BM X) (σ : M.Policy)
    (h : M.adp.IsGreedy v σ) : ∀ x, ∀ a ∈ M.Γ x, M.obj v (x, a) ≤ M.obj v (x, σ.1 x) := by
  classical
  intro x a ha
  have hm : Measurable (Function.update σ.1 x a) := by
    rw [show Function.update σ.1 x a = Set.piecewise {x} (fun _ => a) σ.1 from
      (Set.piecewise_singleton x (fun _ => a) σ.1).symm]
    exact Measurable.piecewise (measurableSet_singleton x) measurable_const σ.2.1
  let τ : M.Policy := ⟨Function.update σ.1 x a, hm, fun y => by
    by_cases hy : y = x
    · subst hy; simpa using ha
    · rw [Function.update_of_ne hy]; exact σ.2.2 y⟩
  have := h τ x
  rwa [T_apply_obj, T_apply_obj, show τ.1 x = a from Function.update_self x a σ.1] at this

/-- Iterating `T_σ` from `0` gives the partial sums `∑_{t < n} K_σ^t r_σ`. -/
theorem iterate_T_zero (σ : M.Policy) (n : ℕ) :
    (M.adp.T σ)^[n] 0 = ∑ t ∈ Finset.range n, (M.K σ ^ t) (M.rσ σ) := by
  induction n with
  | zero => simp
  | succ n ih =>
    rw [Function.iterate_succ_apply', ih, Finset.sum_range_succ']
    change M.rσ σ + M.K σ (∑ t ∈ Finset.range n, (M.K σ ^ t) (M.rσ σ)) = _
    rw [map_sum, add_comm]
    congr 1
    refine Finset.sum_congr rfl fun t _ => ?_
    rw [pow_succ']
    rfl

/-- If `ρ(K_σ) < 1`, then `T_σ` is globally stable. -/
theorem globallyStable_T (σ : M.Policy) (hρ : BanachLattice.specRad (M.K σ) < 1) :
    GloballyStable (M.adp.T σ) := by
  have : Nonempty (BM X) := ⟨0⟩
  have hι : BanachLattice.IsIsoOrderEmbedding (id : BM X → BM X) :=
    ⟨fun v w => dist_eq_norm v w, fun _ _ => Iff.rfl⟩
  exact (BanachLattice.theorem_4_1_4 hι ⟨BanachLattice.example_4_1_1 (M.K_isPositive σ) hρ,
    M.isAdditive.abs_sub σ⟩).1

/-- (6.5)–(6.6) (p. 191): if `ρ(K_σ) < 1`, the `σ`-value function is the unique solution of
`v_σ = r_σ + K_σ v_σ` and equals `∑_{t ≥ 0} K_σ^t r_σ`. -/
theorem lifetime_value (σ : M.Policy) (hρ : BanachLattice.specRad (M.K σ) < 1) :
    ∃ vσ, M.adp.T σ vσ = vσ ∧ (∀ w, M.adp.T σ w = w → w = vσ) ∧
      Tendsto (fun n => ∑ t ∈ Finset.range n, (M.K σ ^ t) (M.rσ σ)) atTop (𝓝 vσ) := by
  obtain ⟨u, hu, huniq, hlim⟩ := M.globallyStable_T σ hρ
  refine ⟨u, hu, huniq, ?_⟩
  refine (hlim 0).congr fun n => ?_
  exact M.iterate_T_zero σ n

/-! ### Examples -/

/-- **Example 6.1.4** (p. 190): the firm valuation problem with state-dependent discounting as an
LDP, `A = {0, 1}` (`true` = exit), `r(x, a) = as + (1 − a)π(x)` and
`K(x, a, dx') = (1 − a)β(x)P(x, dx')`. -/
noncomputable def firm (P : Kernel X X) [IsMarkovKernel P] (s : ℝ) (π βf : BM X)
    (hβ : 0 ≤ βf) : LDP X Bool where
  Γ _ := univ
  r := ⟨fun p => if p.2 then s else π.toFun p.1,
    Measurable.ite (measurableSet_eq_fun measurable_snd measurable_const) measurable_const
      (π.measurable'.comp measurable_fst),
    ⟨|s| + ‖π‖, fun p => by
      split_ifs
      · exact le_add_of_nonneg_right (norm_nonneg _)
      · exact (BM.abs_le_norm π _).trans (le_add_of_nonneg_left (abs_nonneg _))⟩⟩
  β := ⟨fun p => if p.2 then 0 else βf.toFun p.1,
    Measurable.ite (measurableSet_eq_fun measurable_snd measurable_const) measurable_const
      (βf.measurable'.comp measurable_fst),
    ⟨‖βf‖, fun p => by
      split_ifs
      · simp
      · exact BM.abs_le_norm βf _⟩⟩
  β_nonneg p := by
    change 0 ≤ if p.2 then (0 : ℝ) else βf.toFun p.1
    split_ifs
    · exact le_rfl
    · exact hβ _
  P := P.comap Prod.fst measurable_fst
  exists_policy := ⟨fun _ => false, measurable_const, fun _ => Set.mem_univ _⟩

/-- The firm policy operator: `(T_σ v)(x) = s` if `σ(x)` is exit, and
`π(x) + β(x) ∫ v(x')P(x, dx')` otherwise. -/
theorem firm_T_apply (P : Kernel X X) [IsMarkovKernel P] (s : ℝ) (π βf : BM X) (hβ : 0 ≤ βf)
    (σ : (firm P s π βf hβ).Policy) (v : BM X) (x : X) :
    ((firm P s π βf hβ).adp.T σ v).toFun x =
      if σ.1 x then s else π.toFun x + βf.toFun x * ∫ x', v.toFun x' ∂(P x) := by
  rw [T_apply]
  change (if σ.1 x then s else π.toFun x) + (if σ.1 x then (0 : ℝ) else βf.toFun x) *
    ∫ x', v.toFun x' ∂(P x) = _
  split_ifs <;> simp

end LDP

/-- **Example 6.1.6** (p. 191): the risk-sensitive policy operator
`(T_σ v)(x) = r(x, σ(x)) + (β/θ) ln ∑_{x'} exp(θv(x'))P(x, σ(x), x')` is not affine in `v`, so it
does not have the LDP form `r_σ + K_σ v`. Two states, `P` uniform, `β = θ = 1`, `r = 0`: then
`T(2v) − T0 ≠ 2(Tv − T0)` at `v = (1, 0)`. -/
theorem example_6_1_6 :
    let T : (Bool → ℝ) → ℝ := fun v => Real.log ((Real.exp (v true) + Real.exp (v false)) / 2)
    T (fun b => 2 * if b then 1 else 0) - T 0 ≠
      2 * (T (fun b => if b then 1 else 0) - T 0) := by
  intro T
  simp only [T, Pi.zero_apply, Real.exp_zero, ite_true, mul_one]
  norm_num
  intro h
  -- `log((e² + 1)/2) = 2 log((e + 1)/2)` gives `(e² + 1)/2 = ((e + 1)/2)²`, i.e. `(e − 1)² = 0`
  have h1 : (Real.exp 2 + 1) / 2 = ((Real.exp 1 + 1) / 2) ^ 2 := by
    have hpos1 : 0 < (Real.exp 2 + 1) / 2 := by positivity
    have hpos2 : 0 < ((Real.exp 1 + 1) / 2) ^ 2 := by positivity
    rw [← Real.exp_log hpos1, ← Real.exp_log hpos2, Real.log_pow, h]
    push_cast
    ring_nf
  have he : Real.exp 2 = Real.exp 1 ^ 2 := by rw [← Real.exp_nat_mul]; norm_num
  rw [he] at h1
  have h3 : (Real.exp 1 - 1) ^ 2 = 0 := by nlinarith
  have h4 : Real.exp 1 - 1 = 0 := pow_eq_zero_iff two_ne_zero |>.1 h3
  have h5 := Real.add_one_lt_exp (x := (1 : ℝ)) one_ne_zero
  linarith

end SargentStachurski.AdditionalApplications
