/-
Copyright (c) 2026 Robert Kirkby. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Robert Kirkby
-/
import AdditionalApplications.UniqueMax
import AdditionalApplications.Algorithms

/-!
# Recursive decision processes

Sargent and Stachurski, *Dynamic Programming*, Volume 2, §7.1.1.1 (pp. 208–209), §7.1.2.2
(pp. 213–214) and §7.1.3 (pp. 215–217).

* An RDP `(Γ, V, B)`: a nonempty feasible correspondence `Γ`, a value space `V` of functions
  `X → ℝ` with the pointwise order, and an aggregator `B` that is monotone (7.2) and consistent
  (7.3). The value space is a type `V` with an order embedding `ev : V → ℝ^X`; the book's
  `V ⊆ ℝ^X` is the case where `V` is a subtype and `ev` the inclusion, and the same definition
  covers `bX`, `bℓX₊` and other spaces with their own structure. The aggregator is a function of
  `(x, a)` and of a function `X → ℝ`; only its values on `G × ev(V)` matter.
* §7.1.2.2: the generated ADP `(V, 𝕋)` with `(T_σ v)(x) = B(x, σ(x), v)`; `σ` is `v`-greedy iff
  (7.10) holds; a policy attaining `max_{a ∈ Γ(x)} B(x, a, v)` at every `x` is `v`-greedy and then
  `(Tv)(x) = max_{a ∈ Γ(x)} B(x, a, v)` (7.11).
* **Exercise 7.1.5**: an order isomorphism `φ` of the value ranges with
  `B(x, a, v) = φ⁻¹[B̂(x, a, φ ∘ v)]` (7.12) makes the generated ADPs isomorphic.
* **Lemma 7.1.1** (finite actions) and **Lemma 7.1.2** (continuous actions, with Theorem A.3.3 as
  the hypothesis `HasMaxSelections Γ`): greedy policies are the pointwise maximizers, they exist,
  and the Bellman operator is `(Tv)(x) = max_{a ∈ Γ(x)} B(x, a, v)`. Lemma 7.1.1 needs
  `x ↦ B(x, a, v)` and `{x | a ∈ Γ(x)}` measurable, as its proof uses.
-/

open Set Function Filter Topology MeasureTheory

namespace SargentStachurski.AdditionalApplications

/-- The feasible policies of `Γ` (§7.1.1.1): measurable `σ : X → A` with `σ(x) ∈ Γ(x)`. -/
abbrev FeasiblePolicy {X A : Type*} [MeasurableSpace X] [MeasurableSpace A] (Γ : X → Set A) :
    Type _ :=
  {σ : X → A // Measurable σ ∧ ∀ x, σ x ∈ Γ x}

/-- A **recursive decision process** `(Γ, V, B)` (§7.1.1.1): a nonempty feasible correspondence
`Γ`, a value space `V` ordered pointwise through `ev : V → ℝ^X`, and an aggregator `B` satisfying
the monotonicity condition (7.2) and the consistency condition (7.3). -/
structure RDP (X A V : Type*) [MeasurableSpace X] [MeasurableSpace A] [PartialOrder V] where
  /-- the value space as functions `X → ℝ` -/
  ev : V → X → ℝ
  /-- the order of `V` is the pointwise order -/
  ev_le_iff : ∀ v w : V, v ≤ w ↔ ev v ≤ ev w
  /-- the feasible correspondence -/
  Γ : X → Set A
  /-- the aggregator -/
  B : X → A → (X → ℝ) → ℝ
  /-- the monotonicity condition (7.2) -/
  mono : ∀ x, ∀ a ∈ Γ x, ∀ v w : V, v ≤ w → B x a (ev v) ≤ B x a (ev w)
  /-- the consistency condition (7.3) -/
  consistent : ∀ σ : X → A, Measurable σ → (∀ x, σ x ∈ Γ x) → ∀ v : V,
    ∃ w : V, ev w = fun x => B x (σ x) (ev v)
  /-- `Γ` is nonempty: a feasible policy exists -/
  exists_policy : ∃ σ : X → A, Measurable σ ∧ ∀ x, σ x ∈ Γ x

namespace RDP

variable {X A V : Type*} [MeasurableSpace X] [MeasurableSpace A] [PartialOrder V]
  (R : RDP X A V)

/-- The feasible policies `Σ`. -/
abbrev Policy : Type _ := FeasiblePolicy R.Γ

theorem ev_injective : Injective R.ev := fun v w h =>
  le_antisymm ((R.ev_le_iff v w).2 h.le) ((R.ev_le_iff w v).2 h.ge)

theorem nonempty_Γ (x : X) : (R.Γ x).Nonempty :=
  ⟨R.exists_policy.choose x, R.exists_policy.choose_spec.2 x⟩

/-- The policy operator `(T_σ v)(x) = B(x, σ(x), v)` (§7.1.2.2). -/
noncomputable def T (σ : R.Policy) (v : V) : V := (R.consistent σ.1 σ.2.1 σ.2.2 v).choose

theorem ev_T (σ : R.Policy) (v : V) (x : X) : R.ev (R.T σ v) x = R.B x (σ.1 x) (R.ev v) :=
  congrFun (R.consistent σ.1 σ.2.1 σ.2.2 v).choose_spec x

/-- The ADP `(V, 𝕋)` generated by the RDP (§7.1.2.2). -/
noncomputable def adp : ADP V R.Policy where
  T := R.T
  mono σ v w h := (R.ev_le_iff _ _).2 fun x => by
    rw [R.ev_T, R.ev_T]
    exact R.mono x _ (σ.2.2 x) v w h
  nonempty := ⟨⟨R.exists_policy.choose, R.exists_policy.choose_spec⟩⟩

theorem ev_adp_T (σ : R.Policy) (v : V) (x : X) :
    R.ev (R.adp.T σ v) x = R.B x (σ.1 x) (R.ev v) :=
  R.ev_T σ v x

/-- (7.10): `σ` is `v`-greedy iff `B(x, τ(x), v) ≤ B(x, σ(x), v)` for all `τ ∈ Σ` and `x ∈ X`. -/
theorem isGreedy_iff (v : V) (σ : R.Policy) :
    R.adp.IsGreedy v σ ↔ ∀ τ : R.Policy, ∀ x, R.B x (τ.1 x) (R.ev v) ≤ R.B x (σ.1 x) (R.ev v) := by
  refine forall_congr' fun τ => ?_
  rw [R.ev_le_iff]
  refine forall_congr' fun x => ?_
  rw [R.ev_adp_T, R.ev_adp_T]

/-- `σ` attains `max_{a ∈ Γ(x)} B(x, a, v)` at every `x` ((7.16), (7.18)). -/
def IsArgmax (v : V) (σ : R.Policy) : Prop :=
  ∀ x, ∀ a ∈ R.Γ x, R.B x a (R.ev v) ≤ R.B x (σ.1 x) (R.ev v)

/-- A policy satisfying (7.16) is `v`-greedy (the easy half of Lemmas 7.1.1 (i) and 7.1.2 (i)). -/
theorem isGreedy_of_isArgmax {v : V} {σ : R.Policy} (h : R.IsArgmax v σ) : R.adp.IsGreedy v σ :=
  (R.isGreedy_iff v σ).2 fun τ x => h x _ (τ.2.2 x)

/-- If `σ` attains the maximum at every state, `v ∈ V_G` and the Bellman operator is
`(Tv)(x) = B(x, σ(x), v) = max_{a ∈ Γ(x)} B(x, a, v)` (7.11). -/
theorem bellman_of_isArgmax {v : V} {σ : R.Policy} (h : R.IsArgmax v σ) :
    v ∈ R.adp.VG ∧ (∀ x, R.ev (R.adp.bellman v) x = R.B x (σ.1 x) (R.ev v)) ∧
      ∀ x, IsGreatest ((fun a => R.B x a (R.ev v)) '' R.Γ x) (R.ev (R.adp.bellman v) x) := by
  have hg := R.isGreedy_of_isArgmax h
  have hv : v ∈ R.adp.VG := ⟨σ, hg⟩
  have heq : R.adp.bellman v = R.adp.T σ v := ((R.adp.isGreedy_iff hv σ).1 hg).symm
  have hval : ∀ x, R.ev (R.adp.bellman v) x = R.B x (σ.1 x) (R.ev v) := fun x => by
    rw [heq, R.ev_adp_T]
  refine ⟨hv, hval, fun x => ⟨⟨σ.1 x, σ.2.2 x, (hval x).symm⟩, ?_⟩⟩
  rintro _ ⟨a, ha, rfl⟩
  rw [hval]
  exact h x a ha

/-- If some policy attains the maximum at every state, the `v`-greedy policies are exactly the
policies that do ((7.16), (7.18)): the hard half of Lemmas 7.1.1 (i) and 7.1.2 (i), by
Lemma 2.1.1. -/
theorem isGreedy_iff_isArgmax {v : V} {σ₀ : R.Policy} (h₀ : R.IsArgmax v σ₀) (σ : R.Policy) :
    R.adp.IsGreedy v σ ↔ R.IsArgmax v σ := by
  refine ⟨fun hg x a ha => ?_, R.isGreedy_of_isArgmax⟩
  obtain ⟨hv, hval, -⟩ := R.bellman_of_isArgmax h₀
  have heq : R.adp.T σ v = R.adp.bellman v := (R.adp.isGreedy_iff hv σ).1 hg
  have hx : R.B x (σ.1 x) (R.ev v) = R.B x (σ₀.1 x) (R.ev v) := by
    rw [← R.ev_adp_T, heq, hval]
  rw [hx]
  exact h₀ x a ha

/-- **Lemma 7.1.1** (p. 216): if `A` is finite, and `{x | a ∈ Γ(x)}` and `x ↦ B(x, a, v)` are
measurable for each `a` (as the proof uses), then (i) `σ` is `v`-greedy iff it satisfies (7.16),
(ii) a `v`-greedy policy exists, and (iii) `(Tv)(x) = max_{a ∈ Γ(x)} B(x, a, v)` (7.17). -/
theorem lemma_7_1_1 [Finite A] (hΓ : ∀ a, MeasurableSet {x | a ∈ R.Γ x}) (v : V)
    (hB : ∀ a, Measurable fun x => R.B x a (R.ev v)) :
    (∀ σ : R.Policy, R.adp.IsGreedy v σ ↔ R.IsArgmax v σ) ∧ (∃ σ, R.adp.IsGreedy v σ) ∧
      ∀ x, IsGreatest ((fun a => R.B x a (R.ev v)) '' R.Γ x) (R.ev (R.adp.bellman v) x) := by
  obtain ⟨σ, hσm, hσΓ, hmax⟩ := exists_measurable_argmax hΓ R.nonempty_Γ hB
  let σp : R.Policy := ⟨σ, hσm, hσΓ⟩
  have h₀ : R.IsArgmax v σp := hmax
  exact ⟨R.isGreedy_iff_isArgmax h₀, ⟨σp, R.isGreedy_of_isArgmax h₀⟩,
    (R.bellman_of_isArgmax h₀).2.2⟩

/-- **Lemma 7.1.2** (p. 217): if `Γ` has the maximum theorem (Theorem A.3.3, `HasMaxSelections`)
and `(x, a) ↦ B(x, a, v)` is continuous on `G`, then (i) `σ` is `v`-greedy iff it satisfies (7.18),
(ii) a `v`-greedy policy exists, (iii) `T` is defined at `v`, `Tv` is continuous and
`(Tv)(x) = max_{a ∈ Γ(x)} B(x, a, v)` (7.19); and a policy that is the unique maximizer at every
state is continuous when `Γ` has the last claim of Theorem A.3.3. -/
theorem lemma_7_1_2 [TopologicalSpace X] [TopologicalSpace A] (hΓ : HasMaxSelections R.Γ)
    (v : V) (hc : ContinuousOn (fun p : X × A => R.B p.1 p.2 (R.ev v)) {p | p.2 ∈ R.Γ p.1}) :
    (∀ σ : R.Policy, R.adp.IsGreedy v σ ↔ R.IsArgmax v σ) ∧ (∃ σ, R.adp.IsGreedy v σ) ∧
      v ∈ R.adp.VG ∧ Continuous (R.ev (R.adp.bellman v)) ∧
      (∀ x, IsGreatest ((fun a => R.B x a (R.ev v)) '' R.Γ x) (R.ev (R.adp.bellman v) x)) ∧
      (HasContinuousUniqueMax R.Γ → ∀ σ : R.Policy, R.IsArgmax v σ →
        (∀ x, ∀ a ∈ R.Γ x, R.B x (σ.1 x) (R.ev v) ≤ R.B x a (R.ev v) → a = σ.1 x) →
        Continuous σ.1) := by
  obtain ⟨σ, hσm, hσΓ, hmax, hcont⟩ := hΓ _ hc
  let σp : R.Policy := ⟨σ, hσm, hσΓ⟩
  have h₀ : R.IsArgmax v σp := hmax
  obtain ⟨hv, hval, hgr⟩ := R.bellman_of_isArgmax h₀
  have hTc : Continuous (R.ev (R.adp.bellman v)) := by
    have : R.ev (R.adp.bellman v) = fun x => R.B x (σ x) (R.ev v) := funext hval
    rw [this]
    exact hcont
  exact ⟨R.isGreedy_iff_isArgmax h₀, ⟨σp, R.isGreedy_of_isArgmax h₀⟩, hv, hTc, hgr,
    fun hU τ hτ huniq => hU _ hc τ.1 τ.2.2 hτ huniq⟩

/-- **Exercise 7.1.5** (p. 214): let `ev(V) ⊆ M^X`, let `φ` be strictly increasing on `M` with
left inverse `φ⁻¹` there, let `V̂ = {φ ∘ v : v ∈ V}`, and let the aggregators be related by (7.12),
`B(x, a, v) = φ⁻¹[B̂(x, a, φ ∘ v)]`. Then `F v = φ ∘ v` is an order isomorphism `V ≃o V̂`
conjugating the policy operators: the generated ADPs are isomorphic. -/
theorem exercise_7_1_5 {V' : Type*} [PartialOrder V'] (R' : RDP X A V') {M : Set ℝ}
    (φ ψ : ℝ → ℝ) (hφ : StrictMonoOn φ M) (hψ : ∀ t ∈ M, ψ (φ t) = t)
    (hM : ∀ v x, R.ev v x ∈ M) (hV : ∀ v : V, ∃ v' : V', R'.ev v' = φ ∘ R.ev v)
    (hV' : ∀ v' : V', ∃ v : V, R'.ev v' = φ ∘ R.ev v)
    (hB : ∀ x, ∀ a ∈ R.Γ x, ∀ v : V, R.B x a (R.ev v) = ψ (R'.B x a (φ ∘ R.ev v))) :
    ∃ F : V ≃o V', (∀ v, R'.ev (F v) = φ ∘ R.ev v) ∧
      ∀ (σ : R.Policy) (σ' : R'.Policy), σ.1 = σ'.1 → ∀ v, F (R.adp.T σ v) = R'.adp.T σ' (F v) := by
  let F : V → V' := fun v => (hV v).choose
  have hF : ∀ v, R'.ev (F v) = φ ∘ R.ev v := fun v => (hV v).choose_spec
  let G : V' → V := fun v' => (hV' v').choose
  have hG : ∀ v', R'.ev v' = φ ∘ R.ev (G v') := fun v' => (hV' v').choose_spec
  -- `φ ∘ ·` is injective and reflects the order on functions with values in `M`
  have hinj : ∀ v w : V, φ ∘ R.ev v = φ ∘ R.ev w → v = w := fun v w h =>
    R.ev_injective (funext fun x => hφ.injOn (hM v x) (hM w x) (congrFun h x))
  have hle : ∀ v w : V, φ ∘ R.ev v ≤ φ ∘ R.ev w ↔ v ≤ w := fun v w => by
    rw [R.ev_le_iff]
    exact forall_congr' fun x => hφ.le_iff_le (hM v x) (hM w x)
  have hGF : ∀ v, G (F v) = v := fun v => hinj _ _ (by rw [← hG, hF])
  have hFG : ∀ v', F (G v') = v' := fun v' => R'.ev_injective (by rw [hF, hG])
  let e : V ≃ V' := ⟨F, G, hGF, hFG⟩
  refine ⟨⟨e, fun {v w} => ?_⟩, hF, fun σ σ' hσ v => R'.ev_injective (funext fun x => ?_)⟩
  · change F v ≤ F w ↔ v ≤ w
    rw [R'.ev_le_iff, hF, hF]
    exact hle v w
  · change R'.ev (F (R.adp.T σ v)) x = R'.ev (R'.adp.T σ' (F v)) x
    rw [hF, Function.comp_apply, R.ev_adp_T, R'.ev_adp_T, hF, hB x _ (σ.2.2 x), ← hσ]
    -- `B̂(x, σ(x), φ ∘ v)` is a value of `T̂_σ(Fv) ∈ V̂ = φ ∘ V`, so lies in `φ(M)`
    obtain ⟨w, hw⟩ := hV' (R'.adp.T σ' (F v))
    have hval : R'.B x (σ.1 x) (φ ∘ R.ev v) = φ (R.ev w x) := by
      rw [← Function.comp_apply (f := φ) (g := R.ev w), ← hw, R'.ev_adp_T, hF, hσ]
    rw [hval, hψ _ (hM w x)]

end RDP

end SargentStachurski.AdditionalApplications
