/-
Copyright (c) 2026 Robert Kirkby. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Robert Kirkby
-/
import RecursiveDecisionProcesses.Optimality

/-!
# Examples of recursive decision processes

Sargent and Stachurski, *Dynamic Programming*, Volume 1, §8.1.1 (pp. 248–251) and
Example 8.1.14 (p. 252).

Every example is an RDP `(Γ, V, B)`; the constructions below check (8.2) and (8.3).

* Example 8.1.1: an MDP `(Γ, β, r, P)` with `B(x, a, v) = r(x, a) + β ∑ v(x')P(x, a, x')`.
* Example 8.1.2: cake eating, `B(x, x', v) = u(x − x') + βv(x')`.
* Example 8.1.3 and Exercise 8.1.1: optimal stopping, `B(x, a, v) = e(x)` when stopping and
  `c(x) + β(Pv)(x)` when continuing; the Bellman operator is (8.5).
* Example 8.1.4 and Exercise 8.1.2: the Stokey–Lucas form (8.7) with exogenous `Z` and
  endogenous `Y` is an MDP.
* Example 8.1.5 and Exercise 8.1.3: state-dependent discounting (8.8).
* Example 8.1.6 and Exercise 8.1.4: risk-sensitive preferences (8.9), for every `θ ≠ 0`.
* Example 8.1.7 and Exercise 8.1.5: Epstein–Zin preferences (8.10) on `V = (0, ∞)^X`.
* Example 8.1.8: shortest paths, `B(x, x', v) = c(x, x') + v(x')` (and, for §8.3.5.2,
  `c(x, x') + βv(x')`); Example 8.1.14: a two-cycle of positive total cost makes it ill-posed.
* Quantile preferences (Exercise 8.3.1) and the quantile job search model (§8.2.1.4).

Kernels `P : X → A → X → ℝ` are read at a fixed action as the matrix `P_a(x, x') = P(x, a, x')`
(`kernelAt`), whose row `x` is all that `B(x, a, ·)` uses.
-/

open Finset Matrix Function Set

namespace SargentStachurski.RecursiveDecisionProcesses

variable {X A : Type*} [Fintype X] [Fintype A]

/-- The matrix `P_a(x, x') = P(x, a, x')` of a kernel at a fixed action `a`. -/
def kernelAt (P : X → A → X → ℝ) (a : A) : Matrix X X ℝ := Matrix.of fun x x' => P x a x'

omit [Fintype X] [Fintype A] in
theorem kernelAt_apply (P : X → A → X → ℝ) (a : A) (x x' : X) : kernelAt P a x x' = P x a x' :=
  rfl

omit [Fintype A] in
/-- A kernel whose rows are distributions is Markov at every action. -/
theorem isMarkov_kernelAt {P : X → A → X → ℝ} (h0 : ∀ x a x', 0 ≤ P x a x')
    (h1 : ∀ x a, ∑ x', P x a x' = 1) (a : A) : IsMarkov (kernelAt P a) :=
  ⟨fun x x' => h0 x a x', fun x => h1 x a⟩

/-! ### Markov decision processes (Example 8.1.1) -/

/-- A Markov decision process `M = (Γ, β, r, P)` (§5.1.1, restated from
`FiniteStates/MarkovDecisionProcesses`). -/
structure MDP (X A : Type*) [Fintype X] [Fintype A] where
  Γ : X → Finset A
  Γ_nonempty : ∀ x, (Γ x).Nonempty
  β : ℝ
  β_pos : 0 < β
  β_lt_one : β < 1
  r : X → A → ℝ
  P : X → A → X → ℝ
  P_nonneg : ∀ x a x', 0 ≤ P x a x'
  P_rowsum : ∀ x a, ∑ x', P x a x' = 1

namespace MDP

variable (M : MDP X A)

/-- `P_a` is Markov. -/
theorem isMarkov_P (a : A) : IsMarkov (kernelAt M.P a) :=
  isMarkov_kernelAt M.P_nonneg M.P_rowsum a

/-- The closed-loop matrix `P_σ(x, x') = P(x, σ(x), x')`. -/
def Pσ (σ : X → A) : Matrix X X ℝ := Matrix.of fun x x' => M.P x (σ x) x'

/-- `P_σ` is Markov. -/
theorem isMarkov_Pσ (σ : X → A) : IsMarkov (M.Pσ σ) :=
  ⟨fun x x' => M.P_nonneg x (σ x) x', fun x => M.P_rowsum x (σ x)⟩

/-- The reward under `σ`, `r_σ(x) = r(x, σ(x))`. -/
def rσ (σ : X → A) : X → ℝ := fun x => M.r x (σ x)

/-- **Example 8.1.1** (p. 248), (8.4): the RDP generated by an MDP, with `V = ℝ^X` and
`B(x, a, v) = r(x, a) + β ∑ v(x')P(x, a, x')`. -/
def toRDP : RDP X A where
  Γ := M.Γ
  Γ_nonempty := M.Γ_nonempty
  V := univ
  B := fun x a v => M.r x a + M.β * ∑ x', v x' * M.P x a x'
  mono := fun x a _ _ _ _ _ hvw => add_le_add le_rfl (mul_le_mul_of_nonneg_left
    (sum_le_sum fun x' _ => mul_le_mul_of_nonneg_right (hvw x') (M.P_nonneg x a x')) M.β_pos.le)
  consistent := fun _ _ _ _ => mem_univ _

theorem toRDP_B (x : X) (a : A) (v : X → ℝ) :
    M.toRDP.B x a v = M.r x a + M.β * ∑ x', v x' * M.P x a x' := rfl

/-- The policy operator of the MDP RDP is the affine map `T_σ v = r_σ + βP_σ v` (5.19). -/
theorem toRDP_Tσ (σ : X → A) (v : X → ℝ) :
    M.toRDP.Tσ σ v = affineOp (M.β • M.Pσ σ) (M.rσ σ) v := by
  funext x
  simp only [RDP.Tσ, toRDP, affineOp, Pi.add_apply, mulVec, dotProduct, Matrix.smul_apply,
    smul_eq_mul, Pσ, Matrix.of_apply, rσ, Finset.mul_sum]
  rw [add_comm]
  congr 1
  exact sum_congr rfl fun x' _ => by ring

end MDP

/-! ### Cake eating (Example 8.1.2) -/

/-- **Example 8.1.2** (p. 248): cake eating on a finite set of sizes `size : X → ℝ`, with
`Γ(x) = {x' : x' ≤ x}`, `V = ℝ^X` and `B(x, x', v) = u(x − x') + βv(x')`, `β ≥ 0`. -/
noncomputable def cakeEating (size : X → ℝ) (u : ℝ → ℝ) {β : ℝ} (hβ : 0 ≤ β) : RDP X X where
  Γ := fun x => univ.filter fun x' => size x' ≤ size x
  Γ_nonempty := fun x => ⟨x, by simp⟩
  V := univ
  B := fun x x' v => u (size x - size x') + β * v x'
  mono := fun _ x' _ _ _ _ _ hvw => add_le_add le_rfl (mul_le_mul_of_nonneg_left (hvw x') hβ)
  consistent := fun _ _ _ _ => mem_univ _

/-! ### Optimal stopping (Example 8.1.3) -/

/-- **Example 8.1.3** (p. 249), (8.6), and **Exercise 8.1.1**: optimal stopping as an RDP with
actions `Bool` (`true` = stop), `Γ(x) = {stop, continue}`, `V = ℝ^X` and `B(x, a, v) = e(x)` if
stopping and `c(x) + β(Pv)(x)` if continuing, for `β ≥ 0` and `P` Markov. -/
def stopping (e c : X → ℝ) {β : ℝ} (hβ : 0 ≤ β) {P : Matrix X X ℝ} (hP : IsMarkov P) :
    RDP X Bool where
  Γ := fun _ => univ
  Γ_nonempty := fun _ => univ_nonempty
  V := univ
  B := fun x a v => bif a then e x else c x + β * (P *ᵥ v) x
  mono := fun x a _ v _ w _ hvw => by
    cases a
    · exact add_le_add le_rfl (mul_le_mul_of_nonneg_left (hP.mulVec_le_mulVec hvw x) hβ)
    · exact le_rfl
  consistent := fun _ _ _ _ => mem_univ _

/-- Example 8.1.3: the Bellman operator of the stopping RDP is (8.5),
`(Tv)(x) = max{e(x), c(x) + β(Pv)(x)}`. -/
theorem stopping_T (e c : X → ℝ) {β : ℝ} (hβ : 0 ≤ β) {P : Matrix X X ℝ} (hP : IsMarkov P)
    (v : X → ℝ) (x : X) : (stopping e c hβ hP).T v x = max (e x) (c x + β * (P *ᵥ v) x) := by
  refine le_antisymm (Finset.sup'_le _ _ fun a _ => ?_) (max_le ?_ ?_)
  · cases a
    · exact le_max_right _ _
    · exact le_max_left _ _
  · exact (stopping e c hβ hP).B_le_T v (a := true) (mem_univ _)
  · exact (stopping e c hβ hP).B_le_T v (a := false) (mem_univ _)

/-! ### The Stokey–Lucas form (Example 8.1.4) -/

/-- **Exercise 8.1.2** (p. 250): the Stokey–Lucas problem (8.7), with states `(y, z)`, exogenous
`Q`-Markov `z`, actions `y' ∈ Γ(y, z)` and reward `F(y, z, y')`, is an MDP with kernel
`P((y, z), y', (y'', z')) = 1{y'' = y'} Q(z, z')`. -/
def stokeyLucas {Y Z : Type*} [Fintype Y] [Fintype Z] [DecidableEq Y] (Γ : Y × Z → Finset Y)
    (hΓ : ∀ x, (Γ x).Nonempty) (F : Y → Z → Y → ℝ) {β : ℝ} (hβ0 : 0 < β) (hβ1 : β < 1)
    {Q : Matrix Z Z ℝ} (hQ : IsMarkov Q) : MDP (Y × Z) Y where
  Γ := Γ
  Γ_nonempty := hΓ
  β := β
  β_pos := hβ0
  β_lt_one := hβ1
  r := fun x y' => F x.1 x.2 y'
  P := fun x y' x' => if x'.1 = y' then Q x.2 x'.2 else 0
  P_nonneg := fun x y' x' => by
    split_ifs
    · exact hQ.nonneg _ _
    · exact le_rfl
  P_rowsum := fun x y' => by
    rw [Fintype.sum_prod_type]
    simp only
    rw [Finset.sum_eq_single y' (fun b _ hb => by simp [hb]) (by simp)]
    simpa using hQ.rowsum x.2

/-- **Example 8.1.4** (p. 249): the aggregator of the Stokey–Lucas RDP is
`B((y, z), y', v) = F(y, z, y') + β ∑ v(y', z')Q(z, z')`, whose Bellman equation is (8.7). -/
theorem stokeyLucas_B {Y Z : Type*} [Fintype Y] [Fintype Z] [DecidableEq Y]
    (Γ : Y × Z → Finset Y) (hΓ : ∀ x, (Γ x).Nonempty) (F : Y → Z → Y → ℝ) {β : ℝ} (hβ0 : 0 < β)
    (hβ1 : β < 1) {Q : Matrix Z Z ℝ} (hQ : IsMarkov Q) (y : Y) (z : Z) (y' : Y)
    (v : Y × Z → ℝ) :
    (stokeyLucas Γ hΓ F hβ0 hβ1 hQ).toRDP.B (y, z) y' v =
      F y z y' + β * ∑ z', v (y', z') * Q z z' := by
  simp only [MDP.toRDP_B, stokeyLucas]
  congr 2
  rw [Fintype.sum_prod_type, Finset.sum_eq_single y' (fun b _ hb => by simp [hb]) (by simp)]
  simp

/-! ### State-dependent discounting, risk sensitivity, Epstein–Zin (Examples 8.1.5–8.1.7) -/

namespace MDP

variable (M : MDP X A)

/-- **Example 8.1.5** (p. 250), (8.8), and **Exercise 8.1.3**: state-dependent discounting,
`B(x, a, v) = r(x, a) + ∑ v(x') b(x, a, x')P(x, a, x')` with `b ≥ 0`, on `V = ℝ^X` (the discount
factor `β` of `M` is not used). -/
def withDiscount (b : X → A → X → ℝ) (hb : ∀ x a x', 0 ≤ b x a x') : RDP X A where
  Γ := M.Γ
  Γ_nonempty := M.Γ_nonempty
  V := univ
  B := fun x a v => M.r x a + ∑ x', v x' * b x a x' * M.P x a x'
  mono := fun x a _ _ _ _ _ hvw => add_le_add le_rfl (sum_le_sum fun x' _ =>
    mul_le_mul_of_nonneg_right (mul_le_mul_of_nonneg_right (hvw x') (hb x a x'))
      (M.P_nonneg x a x'))
  consistent := fun _ _ _ _ => mem_univ _

/-- **Example 8.1.6** (p. 250), (8.9), and **Exercise 8.1.4**: risk-sensitive preferences,
`B(x, a, v) = r(x, a) + (β/θ) ln ∑ exp(θv(x'))P(x, a, x')`, an RDP on `V = ℝ^X` for every
`θ ≠ 0`. -/
noncomputable def riskSensitive {θ : ℝ} (hθ : θ ≠ 0) : RDP X A where
  Γ := M.Γ
  Γ_nonempty := M.Γ_nonempty
  V := univ
  B := fun x a v => M.r x a + M.β * entR θ (kernelAt M.P a) v x
  mono := fun x a _ v _ w _ hvw => add_le_add le_rfl (mul_le_mul_of_nonneg_left
    ((isCertEquiv_entR hθ (M.isMarkov_P a)).mono v (mem_univ _) w (mem_univ _) hvw x)
    M.β_pos.le)
  consistent := fun _ _ _ _ => mem_univ _

/-- The risk-sensitive aggregator written out: (8.9). -/
theorem riskSensitive_B {θ : ℝ} (hθ : θ ≠ 0) (x : X) (a : A) (v : X → ℝ) :
    (M.riskSensitive hθ).B x a v =
      M.r x a + M.β / θ * Real.log (∑ x', Real.exp (θ * v x') * M.P x a x') := by
  simp only [riskSensitive, entR, mulVec_apply_eq, kernelAt_apply]
  ring

/-- **Exercise 8.3.1** (p. 275): quantile preferences, `B(x, a, v) = r(x, a) + β(R^a_τ v)(x)` with
`R^a_τ` the `τ`-quantile operator of `P_a`, an RDP on `V = ℝ^X` for `τ ∈ (0, 1]`. -/
noncomputable def quantile [Nonempty X] {τ : ℝ} (hτ0 : 0 < τ) (hτ1 : τ ≤ 1) : RDP X A where
  Γ := M.Γ
  Γ_nonempty := M.Γ_nonempty
  V := univ
  B := fun x a v => M.r x a + M.β * quantR τ (kernelAt M.P a) v x
  mono := fun x a _ v _ w _ hvw => add_le_add le_rfl (mul_le_mul_of_nonneg_left
    ((isCertEquiv_quantR hτ0 hτ1 (M.isMarkov_P a)).mono v (mem_univ _) w (mem_univ _) hvw x)
    M.β_pos.le)
  consistent := fun _ _ _ _ => mem_univ _

end MDP

omit [Fintype X] in
/-- The Epstein–Zin aggregator `y ↦ (h + by^α)^{1/α}` is increasing on `(0, ∞)` for `h > 0`,
`b ≥ 0` and `α ≠ 0`. -/
theorem ezAgg_monotoneOn {h b α : ℝ} (hh : 0 < h) (hb : 0 ≤ b) (hα : α ≠ 0) :
    MonotoneOn (fun y : ℝ => (h + b * y ^ α) ^ α⁻¹) (Ioi 0) := by
  intro y hy z hz hyz
  have hy' : (0 : ℝ) < y := hy
  have hz' : (0 : ℝ) < z := hz
  have hbase : ∀ t : ℝ, 0 < t → 0 < h + b * t ^ α := fun t ht =>
    add_pos_of_pos_of_nonneg hh (mul_nonneg hb (Real.rpow_nonneg ht.le _))
  rcases lt_or_gt_of_ne hα with hneg | hpos
  · have h1 : z ^ α ≤ y ^ α := Real.rpow_le_rpow_of_nonpos hy' hyz hneg.le
    exact Real.rpow_le_rpow_of_nonpos (hbase z hz') (by nlinarith) (inv_lt_zero.2 hneg).le
  · have h1 : y ^ α ≤ z ^ α := Real.rpow_le_rpow hy'.le hyz hpos.le
    exact Real.rpow_le_rpow (hbase y hy').le (by nlinarith) (inv_pos.2 hpos).le

namespace MDP

variable (M : MDP X A)

/-- **Example 8.1.7** (p. 250), (8.10), and **Exercise 8.1.5**: Epstein–Zin preferences,
`B(x, a, v) = [r(x, a) + β(∑ v(x')^γ P(x, a, x'))^{α/γ}]^{1/α}` for `r ≫ 0` and `α, γ ≠ 0`, an RDP
on `V = (0, ∞)^X`. Here `B(x, a, ·)` is the Koopmans operator (7.14) of `P_a` with `h = r(·, a)`
and `b ≡ β`, evaluated at `x`. -/
noncomputable def epsteinZin (hr : ∀ x a, 0 < M.r x a) {α γ : ℝ} (hα : α ≠ 0) (hγ : γ ≠ 0) :
    RDP X A where
  Γ := M.Γ
  Γ_nonempty := M.Γ_nonempty
  V := posCone X
  B := fun x a v => ezK (fun x => M.r x a) (fun _ => M.β) α γ (kernelAt M.P a) v x
  mono := fun x a _ v hv w hw hvw => ezAgg_monotoneOn (hr x a) M.β_pos.le hα
    (kpR_pos (M.isMarkov_P a) hv x) (kpR_pos (M.isMarkov_P a) hw x)
    ((isCertEquiv_kpR hγ (M.isMarkov_P a)).mono v hv w hw hvw x)
  consistent := fun σ _ _ hv x => ezK_mapsTo (M.isMarkov_P (σ x)) (fun x => (hr x (σ x)).le)
    (fun _ => M.β_pos) α γ hv x

/-- The Epstein–Zin aggregator written out: (8.10). -/
theorem epsteinZin_B (hr : ∀ x a, 0 < M.r x a) {α γ : ℝ} (hα : α ≠ 0) (hγ : γ ≠ 0) (x : X)
    (a : A) {v : X → ℝ} (hv : v ∈ posCone X) :
    (M.epsteinZin hr hα hγ).B x a v =
      (M.r x a + M.β * (∑ x', v x' ^ γ * M.P x a x') ^ (α / γ)) ^ α⁻¹ := by
  have hpos : 0 ≤ ∑ x', v x' ^ γ * M.P x a x' :=
    sum_nonneg fun x' _ => mul_nonneg (Real.rpow_nonneg (hv x').le _) (M.P_nonneg x a x')
  simp only [epsteinZin, ezK, kpR, mulVec_apply_eq, kernelAt_apply]
  rw [← Real.rpow_mul hpos, div_eq_inv_mul]

end MDP

/-! ### Shortest paths (Example 8.1.8) -/

/-- **Example 8.1.8** (p. 251): the shortest path RDP on a graph with successor sets `O(x)`, edge
costs `c` and (for §8.3.5.2) a weight `β ≥ 0` on the cost-to-go: `Γ = O`, `V = ℝ^X` and
`B(x, x', v) = c(x, x') + βv(x')`. Example 8.1.8 itself is `β = 1`. -/
def pathRDP (O : X → Finset X) (hO : ∀ x, (O x).Nonempty) (c : X → X → ℝ) {β : ℝ}
    (hβ : 0 ≤ β) : RDP X X where
  Γ := O
  Γ_nonempty := hO
  V := univ
  B := fun x x' v => c x x' + β * v x'
  mono := fun _ x' _ _ _ _ _ hvw => add_le_add le_rfl (mul_le_mul_of_nonneg_left (hvw x') hβ)
  consistent := fun _ _ _ _ => mem_univ _

/-- **Example 8.1.14** (p. 252): if `x ≠ y` are successors of each other and
`c(x, y) + c(y, x) ≠ 0`, the shortest path RDP is not well-posed: the policy `x ↦ y ↦ x` has no
cost-to-go. -/
theorem pathRDP_not_wellPosed (O : X → Finset X) (hO : ∀ x, (O x).Nonempty)
    (c : X → X → ℝ) {x y : X} (hxy : x ≠ y) (hy : y ∈ O x) (hx : x ∈ O y)
    (hc : c x y + c y x ≠ 0) : ¬ (pathRDP O hO c zero_le_one).WellPosed := by
  classical
  intro hw
  let σ : X → X := fun z => if z = x then y else if z = y then x else (hO z).choose
  have hσ : (pathRDP O hO c zero_le_one).IsFeasible σ := by
    intro z
    change σ z ∈ O z
    by_cases hzx : z = x
    · subst hzx
      simpa [σ] using hy
    · by_cases hzy : z = y
      · subst hzy
        simpa [σ, hzx] using hx
      · simpa [σ, hzx, hzy] using (hO z).choose_spec
  obtain ⟨v, ⟨-, hfix⟩, -⟩ := hw σ hσ
  have h1 : c x y + v y = v x := by
    have := congrFun hfix.eq x
    simpa [RDP.Tσ, pathRDP, σ] using this
  have h2 : c y x + v x = v y := by
    have := congrFun hfix.eq y
    simpa [RDP.Tσ, pathRDP, σ, Ne.symm hxy] using this
  exact hc (by linarith)

end SargentStachurski.RecursiveDecisionProcesses
